#!/usr/bin/env python3
"""Generates Radiant.Text's bidi paired-bracket table from the Unicode Character Database.

    python3 brackets.py --ucd <ucd-dir> --out src/Radiant.Text/Unicode

Reads BidiBrackets.txt (lines "XXXX; YYYY; o|c # name") and writes BidiBracketsData.g.cs: the
bracket code points in order, whether each opens or closes, and each bracket's pair. Rule N0 of
UAX #9 (via BD16) matches brackets under canonical equivalence, so both the bracket and its pair are
written in canonical form, taken from the singleton decompositions in UnicodeData.txt: U+2329 and
U+232A pair with U+3008 and U+3009.
"""
import argparse
import os
import re

ENTRY = re.compile(r'^([0-9A-F]{4,6})\s*;\s*([0-9A-F]{4,6})\s*;\s*([oc])\b')


def singletons(ucd):
    """Maps code points whose canonical decomposition is a single code point to that code point."""
    table = {}
    with open(os.path.join(ucd, 'UnicodeData.txt'), encoding='utf-8') as f:
        for line in f:
            fields = line.split(';')
            decomposition = fields[5].split()
            if len(decomposition) == 1 and not decomposition[0].startswith('<'):
                table[int(fields[0], 16)] = int(decomposition[0], 16)
    return table


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--ucd', required=True)
    ap.add_argument('--out', required=True)
    ap.add_argument('--version', default='16.0.0')
    args = ap.parse_args()

    canonical = singletons(args.ucd)
    rows = []
    with open(os.path.join(args.ucd, 'BidiBrackets.txt'), encoding='utf-8') as f:
        for line in f:
            m = ENTRY.match(line)
            if m:
                cp, pair = int(m.group(1), 16), int(m.group(2), 16)
                rows.append((cp, canonical.get(cp, cp), canonical.get(pair, pair), m.group(3) == 'o'))
    rows.sort()

    def column(values, per):
        lines = [', '.join(values[i:i + per]) for i in range(0, len(values), per)]
        return ',\n            '.join(lines)

    header = (f'// <auto-generated>\n// Generated from Unicode {args.version} BidiBrackets.txt by tools/unicode-data/brackets.py.\n'
              f'// Do not edit; regenerate with tools/unicode-data/generate.sh.\n// </auto-generated>\n\n')
    with open(os.path.join(args.out, 'BidiBracketsData.g.cs'), 'w', encoding='utf-8') as f:
        f.write(header + 'using System;\n\nnamespace Radiant.Text.Unicode;\n\n'
                f'/// <summary>The Bidi_Paired_Bracket and Bidi_Paired_Bracket_Type of every bracket ({len(rows)} brackets).</summary>\n'
                'internal static class BidiBracketsData\n{\n'
                '    /// <summary>The brackets, in code-point order.</summary>\n'
                '    public static ReadOnlySpan<int> CodePoints =>\n        [\n'
                f'            {column([f"0x{r[0]:X}" for r in rows], 12)},\n        ];\n\n'
                '    /// <summary>Each bracket in canonical form, so equivalent brackets compare equal.</summary>\n'
                '    public static ReadOnlySpan<int> Canonical =>\n        [\n'
                f'            {column([f"0x{r[1]:X}" for r in rows], 12)},\n        ];\n\n'
                '    /// <summary>Each bracket\'s pair, in canonical form.</summary>\n'
                '    public static ReadOnlySpan<int> CanonicalPair =>\n        [\n'
                f'            {column([f"0x{r[2]:X}" for r in rows], 12)},\n        ];\n\n'
                '    /// <summary>Whether each bracket opens (the rest close).</summary>\n'
                '    public static ReadOnlySpan<bool> Opens =>\n        [\n'
                f'            {column(["true" if r[3] else "false" for r in rows], 12)},\n        ];\n'
                '}\n')
    print(f'BidiBrackets: {len(rows)} brackets')


if __name__ == '__main__':
    main()
