using System.Linq;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace Radiant.Generators.Tests;

[TestClass]
public class FacetGeneratorTests
{
    private const string Facets = """
        using Radiant.UI.Core;

        namespace App;

        [StyleFacet]
        public interface IHasCornerShape
        {
            /// <summary>The corner radius.</summary>
            float? Corner { get; init; }
        }

        [StyleFacet]
        public interface IHasOutline
        {
            string? OutlineColor { get; init; }
            float OutlineWidth { get; init; }
        }

        """;

    private static string Normalize(string text) => text.Replace("\r\n", "\n").Trim();

    [TestMethod]
    public void AFacetsPropertiesAreGeneratedOnARecordThatImplementsIt()
    {
        var (generated, diagnostics, errors) = GeneratorHarness.Run(Facets + """
            public sealed partial record Card : IHasCornerShape, IHasOutline;
            """);

        Assert.AreEqual(0, diagnostics.Length, string.Join("\n", diagnostics.Select(d => d.ToString())));
        Assert.AreEqual(0, errors.Length, string.Join("\n", errors.Select(d => d.ToString())));
        Assert.AreEqual(Normalize("""
            // <auto-generated/>
            #nullable enable

            namespace App;

            partial record Card
            {
                /// <inheritdoc cref="global::App.IHasCornerShape.Corner"/>
                public float? Corner { get; init; }

                /// <inheritdoc cref="global::App.IHasOutline.OutlineColor"/>
                public string? OutlineColor { get; init; }

                /// <inheritdoc cref="global::App.IHasOutline.OutlineWidth"/>
                public float OutlineWidth { get; init; }
            }
            """), Normalize(generated.Single()));
    }

    [TestMethod]
    public void APropertyTheRecordDeclaresItselfIsNotGenerated()
    {
        var (generated, _, errors) = GeneratorHarness.Run(Facets + """
            public sealed partial record Card : IHasCornerShape
            {
                public float? Corner { get; init; } = 12f;
            }
            """);

        Assert.AreEqual(0, errors.Length);
        Assert.AreEqual(0, generated.Length);
    }

    [TestMethod]
    public void ForwardersCopySetFacetsAndKeepTheTargetsOwnWhereUnset()
    {
        var (generated, diagnostics, errors) = GeneratorHarness.Run(Facets + """
            public sealed partial record Surface : IHasCornerShape, IHasOutline;

            [ForwardFacets(typeof(Surface), "Container", typeof(IHasCornerShape), typeof(IHasOutline))]
            public sealed partial record Button : IHasCornerShape, IHasOutline
            {
                public Surface Part() => ForwardContainer(new Surface());
            }
            """);

        Assert.AreEqual(0, diagnostics.Length);
        Assert.AreEqual(0, errors.Length, string.Join("\n", errors.Select(d => d.ToString())));
        var button = Normalize(generated.Single(g => g.Contains("partial record Button")));
        StringAssert.Contains(button, """
                private global::App.Surface ForwardContainer(global::App.Surface target) => target with
                {
                    Corner = this.Corner ?? target.Corner,
                    OutlineColor = this.OutlineColor ?? target.OutlineColor,
                    OutlineWidth = this.OutlineWidth,
                };
            """.Replace("\r\n", "\n"));
    }

    [TestMethod]
    public void AFacetWhoseTypeMergesIsLayeredOverTheTargetsOwn()
    {
        var (generated, diagnostics, errors) = GeneratorHarness.Run("""
            using Radiant.UI.Core;

            namespace App;

            public readonly record struct Spacing(float? Left, float? Right)
            {
                public Spacing Merge(Spacing over) => new(over.Left ?? Left, over.Right ?? Right);
            }

            [StyleFacet]
            public interface IHasSpacing
            {
                Spacing? Spacing { get; init; }
            }

            public sealed partial record Surface : IHasSpacing;

            [ForwardFacets(typeof(Surface), "Container", typeof(IHasSpacing))]
            public sealed partial record Button : IHasSpacing
            {
                public Surface Part() => ForwardContainer(new Surface { Spacing = new Spacing(8, 8) });
            }

            public static class Probe
            {
                public static Spacing? Run() => new Button { Spacing = new Spacing(null, 20) }.Part().Spacing;
            }
            """);

        Assert.AreEqual(0, diagnostics.Length);
        Assert.AreEqual(0, errors.Length, string.Join("\n", errors.Select(d => d.ToString())));
        StringAssert.Contains(Normalize(generated.Single(g => g.Contains("partial record Button"))),
            "Spacing = this.Spacing is { } spacingOver ? (target.Spacing is { } spacingUnder ? spacingUnder.Merge(spacingOver) : spacingOver) : target.Spacing,");
    }

    [TestMethod]
    public void RecordsInsideTypesAreGeneratedInsideThem()
    {
        var (generated, _, errors) = GeneratorHarness.Run(Facets + """
            public static partial class Outer
            {
                public sealed partial record Inner : IHasCornerShape;
            }
            """);

        Assert.AreEqual(0, errors.Length, string.Join("\n", errors.Select(d => d.ToString())));
        StringAssert.Contains(Normalize(generated.Single()), "partial class Outer\n{\n    partial record Inner\n    {");
    }

    [TestMethod]
    public void ARecordThatIsNotPartialIsReported()
    {
        var (_, diagnostics, _) = GeneratorHarness.Run(Facets + "public sealed record Card : IHasCornerShape;");

        Assert.AreEqual("RAD004", diagnostics.Single().Id);
    }

    [TestMethod]
    public void AClassImplementingAFacetIsReported()
    {
        var (_, diagnostics, _) = GeneratorHarness.Run(Facets + """
            public sealed partial class Card : IHasCornerShape
            {
                public float? Corner { get; init; }
            }
            """);

        Assert.AreEqual("RAD005", diagnostics.Single().Id);
    }

    [TestMethod]
    public void ForwardingAFacetTheTargetLacksIsReported()
    {
        var (_, diagnostics, _) = GeneratorHarness.Run(Facets + """
            public sealed partial record Surface : IHasOutline;

            [ForwardFacets(typeof(Surface), "Container", typeof(IHasCornerShape))]
            public sealed partial record Button : IHasCornerShape;
            """);

        var diagnostic = diagnostics.Single();
        Assert.AreEqual("RAD002", diagnostic.Id);
        StringAssert.Contains(diagnostic.GetMessage(System.Globalization.CultureInfo.InvariantCulture), "'Surface' does not implement the facet 'IHasCornerShape'");
        Assert.AreEqual("Test.cs", diagnostic.Location.SourceTree?.FilePath ?? diagnostic.Location.GetLineSpan().Path);
    }

    [TestMethod]
    public void ForwardingAnInterfaceThatIsNotAFacetIsReported()
    {
        var (_, diagnostics, _) = GeneratorHarness.Run(Facets + """
            public interface IPlain { int X { get; init; } }
            public sealed partial record Surface : IPlain { public int X { get; init; } }

            [ForwardFacets(typeof(Surface), "Container", typeof(IPlain))]
            public sealed partial record Button : IHasCornerShape;
            """);

        Assert.AreEqual("RAD007", diagnostics.Single().Id);
    }

    [TestMethod]
    public void AFacetMemberThatIsNotAnInitPropertyIsReported()
    {
        var (_, diagnostics, _) = GeneratorHarness.Run("""
            using Radiant.UI.Core;

            [StyleFacet]
            public interface IBad
            {
                int Settable { get; set; }
            }

            public sealed partial record Card : IBad
            {
                int IBad.Settable { get; set; }
            }
            """);

        Assert.AreEqual("RAD006", diagnostics.Single().Id);
    }
}
