// <auto-generated>
// Generated from Unicode 16.0.0 extracted/DerivedBinaryProperties.txt by tools/unicode-data/generate.py.
// Do not edit; regenerate with tools/unicode-data/generate.sh.
// </auto-generated>

namespace Radiant.Text.Unicode;

/// <summary>Values of the Unicode property in DerivedBinaryProperties.txt, by their short alias.</summary>
internal enum BidiMirrored : byte
{
    No = 0,
    Yes = 1,
}
