// <auto-generated>
// Generated from Unicode 16.0.0 extracted/DerivedBidiClass.txt by tools/unicode-data/generate.py.
// Do not edit; regenerate with tools/unicode-data/generate.sh.
// </auto-generated>

namespace Radiant.Text.Unicode;

/// <summary>Values of the Unicode property in DerivedBidiClass.txt, by their short alias.</summary>
internal enum BidiClass : byte
{
    AL = 0,
    AN = 1,
    B = 2,
    BN = 3,
    CS = 4,
    EN = 5,
    ES = 6,
    ET = 7,
    FSI = 8,
    L = 9,
    LRE = 10,
    LRI = 11,
    LRO = 12,
    NSM = 13,
    ON = 14,
    PDF = 15,
    PDI = 16,
    R = 17,
    RLE = 18,
    RLI = 19,
    RLO = 20,
    S = 21,
    WS = 22,
}
