// <auto-generated>
// Generated from Unicode 16.0.0 extracted/DerivedEastAsianWidth.txt by tools/unicode-data/generate.py.
// Do not edit; regenerate with tools/unicode-data/generate.sh.
// </auto-generated>

namespace Radiant.Text.Unicode;

/// <summary>Values of the Unicode property in DerivedEastAsianWidth.txt, by their short alias.</summary>
internal enum EastAsianWidth : byte
{
    N = 0,
    F = 1,
    H = 2,
    W = 3,
}
