// <auto-generated>
// Generated from Unicode 16.0.0 extracted/DerivedGeneralCategory.txt by tools/unicode-data/generate.py.
// Do not edit; regenerate with tools/unicode-data/generate.sh.
// </auto-generated>

namespace Radiant.Text.Unicode;

/// <summary>Values of the Unicode property in DerivedGeneralCategory.txt, by their short alias.</summary>
internal enum GeneralCategory : byte
{
    Unlisted = 0,
    Cn = 1,
    Mc = 2,
    Mn = 3,
    Pf = 4,
    Pi = 5,
}
