// <auto-generated>
// Generated from Unicode 16.0.0 auxiliary/GraphemeBreakProperty.txt by tools/unicode-data/generate.py.
// Do not edit; regenerate with tools/unicode-data/generate.sh.
// </auto-generated>

namespace Radiant.Text.Unicode;

/// <summary>Values of the Unicode property in GraphemeBreakProperty.txt, by their short alias.</summary>
internal enum GraphemeBreakProperty : byte
{
    CN = 0,
    CR = 1,
    EX = 2,
    L = 3,
    LF = 4,
    LV = 5,
    LVT = 6,
    PP = 7,
    RI = 8,
    SM = 9,
    T = 10,
    V = 11,
    XX = 12,
    ZWJ = 13,
}
