// <auto-generated>
// Generated from Unicode 16.0.0 DerivedCoreProperties.txt by tools/unicode-data/generate.py.
// Do not edit; regenerate with tools/unicode-data/generate.sh.
// </auto-generated>

namespace Radiant.Text.Unicode;

/// <summary>Values of the Unicode property in DerivedCoreProperties.txt, by their short alias.</summary>
internal enum IndicConjunctBreak : byte
{
    Consonant = 0,
    Extend = 1,
    Linker = 2,
    None = 3,
}
