// <auto-generated>
// Generated from Unicode 16.0.0 extracted/DerivedLineBreak.txt by tools/unicode-data/generate.py.
// Do not edit; regenerate with tools/unicode-data/generate.sh.
// </auto-generated>

namespace Radiant.Text.Unicode;

/// <summary>Values of the Unicode property in DerivedLineBreak.txt, by their short alias.</summary>
internal enum LineBreakClass : byte
{
    AI = 0,
    AK = 1,
    AL = 2,
    AP = 3,
    AS = 4,
    B2 = 5,
    BA = 6,
    BB = 7,
    BK = 8,
    CB = 9,
    CJ = 10,
    CL = 11,
    CM = 12,
    CP = 13,
    CR = 14,
    EB = 15,
    EM = 16,
    EX = 17,
    GL = 18,
    H2 = 19,
    H3 = 20,
    HL = 21,
    HY = 22,
    ID = 23,
    IN = 24,
    IS = 25,
    JL = 26,
    JT = 27,
    JV = 28,
    LF = 29,
    NL = 30,
    NS = 31,
    NU = 32,
    OP = 33,
    PO = 34,
    PR = 35,
    QU = 36,
    RI = 37,
    SA = 38,
    SG = 39,
    SP = 40,
    SY = 41,
    VF = 42,
    VI = 43,
    WJ = 44,
    XX = 45,
    ZW = 46,
    ZWJ = 47,
}
