// <auto-generated>
// Generated from Unicode 16.0.0 auxiliary/WordBreakProperty.txt by tools/unicode-data/generate.py.
// Do not edit; regenerate with tools/unicode-data/generate.sh.
// </auto-generated>

namespace Radiant.Text.Unicode;

/// <summary>Values of the Unicode property in WordBreakProperty.txt, by their short alias.</summary>
internal enum WordBreakProperty : byte
{
    CR = 0,
    DQ = 1,
    EX = 2,
    Extend = 3,
    FO = 4,
    HL = 5,
    KA = 6,
    LE = 7,
    LF = 8,
    MB = 9,
    ML = 10,
    MN = 11,
    NL = 12,
    NU = 13,
    RI = 14,
    SQ = 15,
    WSegSpace = 16,
    XX = 17,
    ZWJ = 18,
}
