// Copyright (c) Meta Platforms, Inc. and affiliates.
// This source code is licensed under the MIT license found in the
// LICENSE file in the root directory of this source tree.
// @generated from yoga/tests/generated/YGAndroidNewsFeed.cpp

using Xunit;
using Facebook.Yoga;
using static Facebook.Yoga.YGNodeAPI;
using static Facebook.Yoga.YGNodeStyleAPI;
using static Facebook.Yoga.YGNodeLayoutAPI;
using static Facebook.Yoga.YGConfigAPI;

namespace Yoga.Tests;

public class YGAndroidNewsFeedTest
{
    [Fact]
    public void android_news_feed()
    {
        var config = YGConfigNew();
        var root = YGNodeNewWithConfig(config);
        YGNodeStyleSetPositionType(root, YGPositionType.Absolute);
        YGNodeStyleSetAlignContent(root, YGAlign.Stretch);
        YGNodeStyleSetWidth(root, 1080);
        var root_child0 = YGNodeNewWithConfig(config);
        YGNodeInsertChild(root, root_child0, 0);
        var root_child0_child0 = YGNodeNewWithConfig(config);
        YGNodeStyleSetAlignContent(root_child0_child0, YGAlign.Stretch);
        YGNodeInsertChild(root_child0, root_child0_child0, 0);
        var root_child0_child0_child0 = YGNodeNewWithConfig(config);
        YGNodeStyleSetAlignContent(root_child0_child0_child0, YGAlign.Stretch);
        YGNodeInsertChild(root_child0_child0, root_child0_child0_child0, 0);
        var root_child0_child0_child0_child0 = YGNodeNewWithConfig(config);
        YGNodeStyleSetFlexDirection(root_child0_child0_child0_child0, YGFlexDirection.Row);
        YGNodeStyleSetAlignItems(root_child0_child0_child0_child0, YGAlign.FlexStart);
        YGNodeStyleSetAlignContent(root_child0_child0_child0_child0, YGAlign.Stretch);
        YGNodeStyleSetMargin(root_child0_child0_child0_child0, YGEdge.Top, 24);
        YGNodeStyleSetMargin(root_child0_child0_child0_child0, YGEdge.Start, 36);
        YGNodeInsertChild(root_child0_child0_child0, root_child0_child0_child0_child0, 0);
        var root_child0_child0_child0_child0_child0 = YGNodeNewWithConfig(config);
        YGNodeStyleSetFlexDirection(root_child0_child0_child0_child0_child0, YGFlexDirection.Row);
        YGNodeStyleSetAlignContent(root_child0_child0_child0_child0_child0, YGAlign.Stretch);
        YGNodeInsertChild(root_child0_child0_child0_child0, root_child0_child0_child0_child0_child0, 0);
        var root_child0_child0_child0_child0_child0_child0 = YGNodeNewWithConfig(config);
        YGNodeStyleSetAlignContent(root_child0_child0_child0_child0_child0_child0, YGAlign.Stretch);
        YGNodeStyleSetWidth(root_child0_child0_child0_child0_child0_child0, 120);
        YGNodeStyleSetHeight(root_child0_child0_child0_child0_child0_child0, 120);
        YGNodeInsertChild(root_child0_child0_child0_child0_child0, root_child0_child0_child0_child0_child0_child0, 0);
        var root_child0_child0_child0_child0_child1 = YGNodeNewWithConfig(config);
        YGNodeStyleSetAlignContent(root_child0_child0_child0_child0_child1, YGAlign.Stretch);
        YGNodeStyleSetFlexShrink(root_child0_child0_child0_child0_child1, 1);
        YGNodeStyleSetMargin(root_child0_child0_child0_child0_child1, YGEdge.Right, 36);
        YGNodeStyleSetPadding(root_child0_child0_child0_child0_child1, YGEdge.Left, 36);
        YGNodeStyleSetPadding(root_child0_child0_child0_child0_child1, YGEdge.Top, 21);
        YGNodeStyleSetPadding(root_child0_child0_child0_child0_child1, YGEdge.Right, 36);
        YGNodeStyleSetPadding(root_child0_child0_child0_child0_child1, YGEdge.Bottom, 18);
        YGNodeInsertChild(root_child0_child0_child0_child0, root_child0_child0_child0_child0_child1, 1);
        var root_child0_child0_child0_child0_child1_child0 = YGNodeNewWithConfig(config);
        YGNodeStyleSetFlexDirection(root_child0_child0_child0_child0_child1_child0, YGFlexDirection.Row);
        YGNodeStyleSetAlignContent(root_child0_child0_child0_child0_child1_child0, YGAlign.Stretch);
        YGNodeStyleSetFlexShrink(root_child0_child0_child0_child0_child1_child0, 1);
        YGNodeInsertChild(root_child0_child0_child0_child0_child1, root_child0_child0_child0_child0_child1_child0, 0);
        var root_child0_child0_child0_child0_child1_child1 = YGNodeNewWithConfig(config);
        YGNodeStyleSetAlignContent(root_child0_child0_child0_child0_child1_child1, YGAlign.Stretch);
        YGNodeStyleSetFlexShrink(root_child0_child0_child0_child0_child1_child1, 1);
        YGNodeInsertChild(root_child0_child0_child0_child0_child1, root_child0_child0_child0_child0_child1_child1, 1);
        var root_child0_child0_child1 = YGNodeNewWithConfig(config);
        YGNodeStyleSetAlignContent(root_child0_child0_child1, YGAlign.Stretch);
        YGNodeInsertChild(root_child0_child0, root_child0_child0_child1, 1);
        var root_child0_child0_child1_child0 = YGNodeNewWithConfig(config);
        YGNodeStyleSetFlexDirection(root_child0_child0_child1_child0, YGFlexDirection.Row);
        YGNodeStyleSetAlignItems(root_child0_child0_child1_child0, YGAlign.FlexStart);
        YGNodeStyleSetAlignContent(root_child0_child0_child1_child0, YGAlign.Stretch);
        YGNodeStyleSetMargin(root_child0_child0_child1_child0, YGEdge.Top, 24);
        YGNodeStyleSetMargin(root_child0_child0_child1_child0, YGEdge.Start, 174);
        YGNodeInsertChild(root_child0_child0_child1, root_child0_child0_child1_child0, 0);
        var root_child0_child0_child1_child0_child0 = YGNodeNewWithConfig(config);
        YGNodeStyleSetFlexDirection(root_child0_child0_child1_child0_child0, YGFlexDirection.Row);
        YGNodeStyleSetAlignContent(root_child0_child0_child1_child0_child0, YGAlign.Stretch);
        YGNodeInsertChild(root_child0_child0_child1_child0, root_child0_child0_child1_child0_child0, 0);
        var root_child0_child0_child1_child0_child0_child0 = YGNodeNewWithConfig(config);
        YGNodeStyleSetAlignContent(root_child0_child0_child1_child0_child0_child0, YGAlign.Stretch);
        YGNodeStyleSetWidth(root_child0_child0_child1_child0_child0_child0, 72);
        YGNodeStyleSetHeight(root_child0_child0_child1_child0_child0_child0, 72);
        YGNodeInsertChild(root_child0_child0_child1_child0_child0, root_child0_child0_child1_child0_child0_child0, 0);
        var root_child0_child0_child1_child0_child1 = YGNodeNewWithConfig(config);
        YGNodeStyleSetAlignContent(root_child0_child0_child1_child0_child1, YGAlign.Stretch);
        YGNodeStyleSetFlexShrink(root_child0_child0_child1_child0_child1, 1);
        YGNodeStyleSetMargin(root_child0_child0_child1_child0_child1, YGEdge.Right, 36);
        YGNodeStyleSetPadding(root_child0_child0_child1_child0_child1, YGEdge.Left, 36);
        YGNodeStyleSetPadding(root_child0_child0_child1_child0_child1, YGEdge.Top, 21);
        YGNodeStyleSetPadding(root_child0_child0_child1_child0_child1, YGEdge.Right, 36);
        YGNodeStyleSetPadding(root_child0_child0_child1_child0_child1, YGEdge.Bottom, 18);
        YGNodeInsertChild(root_child0_child0_child1_child0, root_child0_child0_child1_child0_child1, 1);
        var root_child0_child0_child1_child0_child1_child0 = YGNodeNewWithConfig(config);
        YGNodeStyleSetFlexDirection(root_child0_child0_child1_child0_child1_child0, YGFlexDirection.Row);
        YGNodeStyleSetAlignContent(root_child0_child0_child1_child0_child1_child0, YGAlign.Stretch);
        YGNodeStyleSetFlexShrink(root_child0_child0_child1_child0_child1_child0, 1);
        YGNodeInsertChild(root_child0_child0_child1_child0_child1, root_child0_child0_child1_child0_child1_child0, 0);
        var root_child0_child0_child1_child0_child1_child1 = YGNodeNewWithConfig(config);
        YGNodeStyleSetAlignContent(root_child0_child0_child1_child0_child1_child1, YGAlign.Stretch);
        YGNodeStyleSetFlexShrink(root_child0_child0_child1_child0_child1_child1, 1);
        YGNodeInsertChild(root_child0_child0_child1_child0_child1, root_child0_child0_child1_child0_child1_child1, 1);
        YGNodeCalculateLayout(root, float.NaN, float.NaN, YGDirection.LTR);
        Assert.Equal(0f, YGNodeLayoutGetLeft(root));
        Assert.Equal(0f, YGNodeLayoutGetTop(root));
        Assert.Equal(1080f, YGNodeLayoutGetWidth(root));
        Assert.Equal(240f, YGNodeLayoutGetHeight(root));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child0));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child0));
        Assert.Equal(1080f, YGNodeLayoutGetWidth(root_child0));
        Assert.Equal(240f, YGNodeLayoutGetHeight(root_child0));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child0_child0));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child0_child0));
        Assert.Equal(1080f, YGNodeLayoutGetWidth(root_child0_child0));
        Assert.Equal(240f, YGNodeLayoutGetHeight(root_child0_child0));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child0_child0_child0));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child0_child0_child0));
        Assert.Equal(1080f, YGNodeLayoutGetWidth(root_child0_child0_child0));
        Assert.Equal(144f, YGNodeLayoutGetHeight(root_child0_child0_child0));
        Assert.Equal(36f, YGNodeLayoutGetLeft(root_child0_child0_child0_child0));
        Assert.Equal(24f, YGNodeLayoutGetTop(root_child0_child0_child0_child0));
        Assert.Equal(1044f, YGNodeLayoutGetWidth(root_child0_child0_child0_child0));
        Assert.Equal(120f, YGNodeLayoutGetHeight(root_child0_child0_child0_child0));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child0_child0_child0_child0_child0));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child0_child0_child0_child0_child0));
        Assert.Equal(120f, YGNodeLayoutGetWidth(root_child0_child0_child0_child0_child0));
        Assert.Equal(120f, YGNodeLayoutGetHeight(root_child0_child0_child0_child0_child0));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child0_child0_child0_child0_child0_child0));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child0_child0_child0_child0_child0_child0));
        Assert.Equal(120f, YGNodeLayoutGetWidth(root_child0_child0_child0_child0_child0_child0));
        Assert.Equal(120f, YGNodeLayoutGetHeight(root_child0_child0_child0_child0_child0_child0));
        Assert.Equal(120f, YGNodeLayoutGetLeft(root_child0_child0_child0_child0_child1));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child0_child0_child0_child0_child1));
        Assert.Equal(72f, YGNodeLayoutGetWidth(root_child0_child0_child0_child0_child1));
        Assert.Equal(39f, YGNodeLayoutGetHeight(root_child0_child0_child0_child0_child1));
        Assert.Equal(36f, YGNodeLayoutGetLeft(root_child0_child0_child0_child0_child1_child0));
        Assert.Equal(21f, YGNodeLayoutGetTop(root_child0_child0_child0_child0_child1_child0));
        Assert.Equal(0f, YGNodeLayoutGetWidth(root_child0_child0_child0_child0_child1_child0));
        Assert.Equal(0f, YGNodeLayoutGetHeight(root_child0_child0_child0_child0_child1_child0));
        Assert.Equal(36f, YGNodeLayoutGetLeft(root_child0_child0_child0_child0_child1_child1));
        Assert.Equal(21f, YGNodeLayoutGetTop(root_child0_child0_child0_child0_child1_child1));
        Assert.Equal(0f, YGNodeLayoutGetWidth(root_child0_child0_child0_child0_child1_child1));
        Assert.Equal(0f, YGNodeLayoutGetHeight(root_child0_child0_child0_child0_child1_child1));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child0_child0_child1));
        Assert.Equal(144f, YGNodeLayoutGetTop(root_child0_child0_child1));
        Assert.Equal(1080f, YGNodeLayoutGetWidth(root_child0_child0_child1));
        Assert.Equal(96f, YGNodeLayoutGetHeight(root_child0_child0_child1));
        Assert.Equal(174f, YGNodeLayoutGetLeft(root_child0_child0_child1_child0));
        Assert.Equal(24f, YGNodeLayoutGetTop(root_child0_child0_child1_child0));
        Assert.Equal(906f, YGNodeLayoutGetWidth(root_child0_child0_child1_child0));
        Assert.Equal(72f, YGNodeLayoutGetHeight(root_child0_child0_child1_child0));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child0_child0_child1_child0_child0));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child0_child0_child1_child0_child0));
        Assert.Equal(72f, YGNodeLayoutGetWidth(root_child0_child0_child1_child0_child0));
        Assert.Equal(72f, YGNodeLayoutGetHeight(root_child0_child0_child1_child0_child0));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child0_child0_child1_child0_child0_child0));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child0_child0_child1_child0_child0_child0));
        Assert.Equal(72f, YGNodeLayoutGetWidth(root_child0_child0_child1_child0_child0_child0));
        Assert.Equal(72f, YGNodeLayoutGetHeight(root_child0_child0_child1_child0_child0_child0));
        Assert.Equal(72f, YGNodeLayoutGetLeft(root_child0_child0_child1_child0_child1));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child0_child0_child1_child0_child1));
        Assert.Equal(72f, YGNodeLayoutGetWidth(root_child0_child0_child1_child0_child1));
        Assert.Equal(39f, YGNodeLayoutGetHeight(root_child0_child0_child1_child0_child1));
        Assert.Equal(36f, YGNodeLayoutGetLeft(root_child0_child0_child1_child0_child1_child0));
        Assert.Equal(21f, YGNodeLayoutGetTop(root_child0_child0_child1_child0_child1_child0));
        Assert.Equal(0f, YGNodeLayoutGetWidth(root_child0_child0_child1_child0_child1_child0));
        Assert.Equal(0f, YGNodeLayoutGetHeight(root_child0_child0_child1_child0_child1_child0));
        Assert.Equal(36f, YGNodeLayoutGetLeft(root_child0_child0_child1_child0_child1_child1));
        Assert.Equal(21f, YGNodeLayoutGetTop(root_child0_child0_child1_child0_child1_child1));
        Assert.Equal(0f, YGNodeLayoutGetWidth(root_child0_child0_child1_child0_child1_child1));
        Assert.Equal(0f, YGNodeLayoutGetHeight(root_child0_child0_child1_child0_child1_child1));
        YGNodeCalculateLayout(root, float.NaN, float.NaN, YGDirection.RTL);
        Assert.Equal(0f, YGNodeLayoutGetLeft(root));
        Assert.Equal(0f, YGNodeLayoutGetTop(root));
        Assert.Equal(1080f, YGNodeLayoutGetWidth(root));
        Assert.Equal(240f, YGNodeLayoutGetHeight(root));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child0));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child0));
        Assert.Equal(1080f, YGNodeLayoutGetWidth(root_child0));
        Assert.Equal(240f, YGNodeLayoutGetHeight(root_child0));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child0_child0));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child0_child0));
        Assert.Equal(1080f, YGNodeLayoutGetWidth(root_child0_child0));
        Assert.Equal(240f, YGNodeLayoutGetHeight(root_child0_child0));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child0_child0_child0));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child0_child0_child0));
        Assert.Equal(1080f, YGNodeLayoutGetWidth(root_child0_child0_child0));
        Assert.Equal(144f, YGNodeLayoutGetHeight(root_child0_child0_child0));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child0_child0_child0_child0));
        Assert.Equal(24f, YGNodeLayoutGetTop(root_child0_child0_child0_child0));
        Assert.Equal(1044f, YGNodeLayoutGetWidth(root_child0_child0_child0_child0));
        Assert.Equal(120f, YGNodeLayoutGetHeight(root_child0_child0_child0_child0));
        Assert.Equal(924f, YGNodeLayoutGetLeft(root_child0_child0_child0_child0_child0));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child0_child0_child0_child0_child0));
        Assert.Equal(120f, YGNodeLayoutGetWidth(root_child0_child0_child0_child0_child0));
        Assert.Equal(120f, YGNodeLayoutGetHeight(root_child0_child0_child0_child0_child0));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child0_child0_child0_child0_child0_child0));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child0_child0_child0_child0_child0_child0));
        Assert.Equal(120f, YGNodeLayoutGetWidth(root_child0_child0_child0_child0_child0_child0));
        Assert.Equal(120f, YGNodeLayoutGetHeight(root_child0_child0_child0_child0_child0_child0));
        Assert.Equal(816f, YGNodeLayoutGetLeft(root_child0_child0_child0_child0_child1));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child0_child0_child0_child0_child1));
        Assert.Equal(72f, YGNodeLayoutGetWidth(root_child0_child0_child0_child0_child1));
        Assert.Equal(39f, YGNodeLayoutGetHeight(root_child0_child0_child0_child0_child1));
        Assert.Equal(36f, YGNodeLayoutGetLeft(root_child0_child0_child0_child0_child1_child0));
        Assert.Equal(21f, YGNodeLayoutGetTop(root_child0_child0_child0_child0_child1_child0));
        Assert.Equal(0f, YGNodeLayoutGetWidth(root_child0_child0_child0_child0_child1_child0));
        Assert.Equal(0f, YGNodeLayoutGetHeight(root_child0_child0_child0_child0_child1_child0));
        Assert.Equal(36f, YGNodeLayoutGetLeft(root_child0_child0_child0_child0_child1_child1));
        Assert.Equal(21f, YGNodeLayoutGetTop(root_child0_child0_child0_child0_child1_child1));
        Assert.Equal(0f, YGNodeLayoutGetWidth(root_child0_child0_child0_child0_child1_child1));
        Assert.Equal(0f, YGNodeLayoutGetHeight(root_child0_child0_child0_child0_child1_child1));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child0_child0_child1));
        Assert.Equal(144f, YGNodeLayoutGetTop(root_child0_child0_child1));
        Assert.Equal(1080f, YGNodeLayoutGetWidth(root_child0_child0_child1));
        Assert.Equal(96f, YGNodeLayoutGetHeight(root_child0_child0_child1));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child0_child0_child1_child0));
        Assert.Equal(24f, YGNodeLayoutGetTop(root_child0_child0_child1_child0));
        Assert.Equal(906f, YGNodeLayoutGetWidth(root_child0_child0_child1_child0));
        Assert.Equal(72f, YGNodeLayoutGetHeight(root_child0_child0_child1_child0));
        Assert.Equal(834f, YGNodeLayoutGetLeft(root_child0_child0_child1_child0_child0));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child0_child0_child1_child0_child0));
        Assert.Equal(72f, YGNodeLayoutGetWidth(root_child0_child0_child1_child0_child0));
        Assert.Equal(72f, YGNodeLayoutGetHeight(root_child0_child0_child1_child0_child0));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child0_child0_child1_child0_child0_child0));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child0_child0_child1_child0_child0_child0));
        Assert.Equal(72f, YGNodeLayoutGetWidth(root_child0_child0_child1_child0_child0_child0));
        Assert.Equal(72f, YGNodeLayoutGetHeight(root_child0_child0_child1_child0_child0_child0));
        Assert.Equal(726f, YGNodeLayoutGetLeft(root_child0_child0_child1_child0_child1));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child0_child0_child1_child0_child1));
        Assert.Equal(72f, YGNodeLayoutGetWidth(root_child0_child0_child1_child0_child1));
        Assert.Equal(39f, YGNodeLayoutGetHeight(root_child0_child0_child1_child0_child1));
        Assert.Equal(36f, YGNodeLayoutGetLeft(root_child0_child0_child1_child0_child1_child0));
        Assert.Equal(21f, YGNodeLayoutGetTop(root_child0_child0_child1_child0_child1_child0));
        Assert.Equal(0f, YGNodeLayoutGetWidth(root_child0_child0_child1_child0_child1_child0));
        Assert.Equal(0f, YGNodeLayoutGetHeight(root_child0_child0_child1_child0_child1_child0));
        Assert.Equal(36f, YGNodeLayoutGetLeft(root_child0_child0_child1_child0_child1_child1));
        Assert.Equal(21f, YGNodeLayoutGetTop(root_child0_child0_child1_child0_child1_child1));
        Assert.Equal(0f, YGNodeLayoutGetWidth(root_child0_child0_child1_child0_child1_child1));
        Assert.Equal(0f, YGNodeLayoutGetHeight(root_child0_child0_child1_child0_child1_child1));
        YGNodeFreeRecursive(root);
        YGConfigFree(config);
    }

}

