// Copyright (c) Meta Platforms, Inc. and affiliates.
// This source code is licensed under the MIT license found in the
// LICENSE file in the root directory of this source tree.
// @generated from yoga/tests/generated/YGFlexWrapTest.cpp

using Xunit;
using Facebook.Yoga;
using static Facebook.Yoga.YGNodeAPI;
using static Facebook.Yoga.YGNodeStyleAPI;
using static Facebook.Yoga.YGNodeLayoutAPI;
using static Facebook.Yoga.YGConfigAPI;

namespace Yoga.Tests;

public class YGFlexWrapTest
{
    [Fact]
    public void wrap_column()
    {
        Assert.Skip("Skipped: matches upstream C++ GTEST_SKIP()");
        var config = YGConfigNew();
        var root = YGNodeNewWithConfig(config);
        YGNodeStyleSetPositionType(root, YGPositionType.Absolute);
        YGNodeStyleSetHeight(root, 100);
        YGNodeStyleSetFlexWrap(root, YGWrap.Wrap);
        var root_child0 = YGNodeNewWithConfig(config);
        YGNodeStyleSetHeight(root_child0, 30);
        YGNodeStyleSetWidth(root_child0, 30);
        YGNodeInsertChild(root, root_child0, 0);
        var root_child1 = YGNodeNewWithConfig(config);
        YGNodeStyleSetHeight(root_child1, 30);
        YGNodeStyleSetWidth(root_child1, 30);
        YGNodeInsertChild(root, root_child1, 1);
        var root_child2 = YGNodeNewWithConfig(config);
        YGNodeStyleSetHeight(root_child2, 30);
        YGNodeStyleSetWidth(root_child2, 30);
        YGNodeInsertChild(root, root_child2, 2);
        var root_child3 = YGNodeNewWithConfig(config);
        YGNodeStyleSetHeight(root_child3, 30);
        YGNodeStyleSetWidth(root_child3, 30);
        YGNodeInsertChild(root, root_child3, 3);
        YGNodeCalculateLayout(root, float.NaN, float.NaN, YGDirection.LTR);
        Assert.Equal(0f, YGNodeLayoutGetLeft(root));
        Assert.Equal(0f, YGNodeLayoutGetTop(root));
        Assert.Equal(30f, YGNodeLayoutGetWidth(root));
        Assert.Equal(100f, YGNodeLayoutGetHeight(root));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child0));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child0));
        Assert.Equal(30f, YGNodeLayoutGetWidth(root_child0));
        Assert.Equal(30f, YGNodeLayoutGetHeight(root_child0));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child1));
        Assert.Equal(30f, YGNodeLayoutGetTop(root_child1));
        Assert.Equal(30f, YGNodeLayoutGetWidth(root_child1));
        Assert.Equal(30f, YGNodeLayoutGetHeight(root_child1));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child2));
        Assert.Equal(60f, YGNodeLayoutGetTop(root_child2));
        Assert.Equal(30f, YGNodeLayoutGetWidth(root_child2));
        Assert.Equal(30f, YGNodeLayoutGetHeight(root_child2));
        Assert.Equal(30f, YGNodeLayoutGetLeft(root_child3));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child3));
        Assert.Equal(30f, YGNodeLayoutGetWidth(root_child3));
        Assert.Equal(30f, YGNodeLayoutGetHeight(root_child3));
        YGNodeCalculateLayout(root, float.NaN, float.NaN, YGDirection.RTL);
        Assert.Equal(0f, YGNodeLayoutGetLeft(root));
        Assert.Equal(0f, YGNodeLayoutGetTop(root));
        Assert.Equal(30f, YGNodeLayoutGetWidth(root));
        Assert.Equal(100f, YGNodeLayoutGetHeight(root));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child0));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child0));
        Assert.Equal(30f, YGNodeLayoutGetWidth(root_child0));
        Assert.Equal(30f, YGNodeLayoutGetHeight(root_child0));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child1));
        Assert.Equal(30f, YGNodeLayoutGetTop(root_child1));
        Assert.Equal(30f, YGNodeLayoutGetWidth(root_child1));
        Assert.Equal(30f, YGNodeLayoutGetHeight(root_child1));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child2));
        Assert.Equal(60f, YGNodeLayoutGetTop(root_child2));
        Assert.Equal(30f, YGNodeLayoutGetWidth(root_child2));
        Assert.Equal(30f, YGNodeLayoutGetHeight(root_child2));
        Assert.Equal(-30f, YGNodeLayoutGetLeft(root_child3));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child3));
        Assert.Equal(30f, YGNodeLayoutGetWidth(root_child3));
        Assert.Equal(30f, YGNodeLayoutGetHeight(root_child3));
        YGNodeFreeRecursive(root);
        YGConfigFree(config);
    }

    [Fact]
    public void wrap_row()
    {
        var config = YGConfigNew();
        var root = YGNodeNewWithConfig(config);
        YGNodeStyleSetPositionType(root, YGPositionType.Absolute);
        YGNodeStyleSetWidth(root, 100);
        YGNodeStyleSetFlexDirection(root, YGFlexDirection.Row);
        YGNodeStyleSetFlexWrap(root, YGWrap.Wrap);
        var root_child0 = YGNodeNewWithConfig(config);
        YGNodeStyleSetHeight(root_child0, 30);
        YGNodeStyleSetWidth(root_child0, 30);
        YGNodeInsertChild(root, root_child0, 0);
        var root_child1 = YGNodeNewWithConfig(config);
        YGNodeStyleSetHeight(root_child1, 30);
        YGNodeStyleSetWidth(root_child1, 30);
        YGNodeInsertChild(root, root_child1, 1);
        var root_child2 = YGNodeNewWithConfig(config);
        YGNodeStyleSetHeight(root_child2, 30);
        YGNodeStyleSetWidth(root_child2, 30);
        YGNodeInsertChild(root, root_child2, 2);
        var root_child3 = YGNodeNewWithConfig(config);
        YGNodeStyleSetHeight(root_child3, 30);
        YGNodeStyleSetWidth(root_child3, 30);
        YGNodeInsertChild(root, root_child3, 3);
        YGNodeCalculateLayout(root, float.NaN, float.NaN, YGDirection.LTR);
        Assert.Equal(0f, YGNodeLayoutGetLeft(root));
        Assert.Equal(0f, YGNodeLayoutGetTop(root));
        Assert.Equal(100f, YGNodeLayoutGetWidth(root));
        Assert.Equal(60f, YGNodeLayoutGetHeight(root));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child0));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child0));
        Assert.Equal(30f, YGNodeLayoutGetWidth(root_child0));
        Assert.Equal(30f, YGNodeLayoutGetHeight(root_child0));
        Assert.Equal(30f, YGNodeLayoutGetLeft(root_child1));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child1));
        Assert.Equal(30f, YGNodeLayoutGetWidth(root_child1));
        Assert.Equal(30f, YGNodeLayoutGetHeight(root_child1));
        Assert.Equal(60f, YGNodeLayoutGetLeft(root_child2));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child2));
        Assert.Equal(30f, YGNodeLayoutGetWidth(root_child2));
        Assert.Equal(30f, YGNodeLayoutGetHeight(root_child2));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child3));
        Assert.Equal(30f, YGNodeLayoutGetTop(root_child3));
        Assert.Equal(30f, YGNodeLayoutGetWidth(root_child3));
        Assert.Equal(30f, YGNodeLayoutGetHeight(root_child3));
        YGNodeCalculateLayout(root, float.NaN, float.NaN, YGDirection.RTL);
        Assert.Equal(0f, YGNodeLayoutGetLeft(root));
        Assert.Equal(0f, YGNodeLayoutGetTop(root));
        Assert.Equal(100f, YGNodeLayoutGetWidth(root));
        Assert.Equal(60f, YGNodeLayoutGetHeight(root));
        Assert.Equal(70f, YGNodeLayoutGetLeft(root_child0));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child0));
        Assert.Equal(30f, YGNodeLayoutGetWidth(root_child0));
        Assert.Equal(30f, YGNodeLayoutGetHeight(root_child0));
        Assert.Equal(40f, YGNodeLayoutGetLeft(root_child1));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child1));
        Assert.Equal(30f, YGNodeLayoutGetWidth(root_child1));
        Assert.Equal(30f, YGNodeLayoutGetHeight(root_child1));
        Assert.Equal(10f, YGNodeLayoutGetLeft(root_child2));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child2));
        Assert.Equal(30f, YGNodeLayoutGetWidth(root_child2));
        Assert.Equal(30f, YGNodeLayoutGetHeight(root_child2));
        Assert.Equal(70f, YGNodeLayoutGetLeft(root_child3));
        Assert.Equal(30f, YGNodeLayoutGetTop(root_child3));
        Assert.Equal(30f, YGNodeLayoutGetWidth(root_child3));
        Assert.Equal(30f, YGNodeLayoutGetHeight(root_child3));
        YGNodeFreeRecursive(root);
        YGConfigFree(config);
    }

    [Fact]
    public void wrap_row_align_items_flex_end()
    {
        var config = YGConfigNew();
        var root = YGNodeNewWithConfig(config);
        YGNodeStyleSetPositionType(root, YGPositionType.Absolute);
        YGNodeStyleSetWidth(root, 100);
        YGNodeStyleSetFlexDirection(root, YGFlexDirection.Row);
        YGNodeStyleSetFlexWrap(root, YGWrap.Wrap);
        YGNodeStyleSetAlignItems(root, YGAlign.FlexEnd);
        var root_child0 = YGNodeNewWithConfig(config);
        YGNodeStyleSetHeight(root_child0, 10);
        YGNodeStyleSetWidth(root_child0, 30);
        YGNodeInsertChild(root, root_child0, 0);
        var root_child1 = YGNodeNewWithConfig(config);
        YGNodeStyleSetHeight(root_child1, 20);
        YGNodeStyleSetWidth(root_child1, 30);
        YGNodeInsertChild(root, root_child1, 1);
        var root_child2 = YGNodeNewWithConfig(config);
        YGNodeStyleSetHeight(root_child2, 30);
        YGNodeStyleSetWidth(root_child2, 30);
        YGNodeInsertChild(root, root_child2, 2);
        var root_child3 = YGNodeNewWithConfig(config);
        YGNodeStyleSetHeight(root_child3, 30);
        YGNodeStyleSetWidth(root_child3, 30);
        YGNodeInsertChild(root, root_child3, 3);
        YGNodeCalculateLayout(root, float.NaN, float.NaN, YGDirection.LTR);
        Assert.Equal(0f, YGNodeLayoutGetLeft(root));
        Assert.Equal(0f, YGNodeLayoutGetTop(root));
        Assert.Equal(100f, YGNodeLayoutGetWidth(root));
        Assert.Equal(60f, YGNodeLayoutGetHeight(root));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child0));
        Assert.Equal(20f, YGNodeLayoutGetTop(root_child0));
        Assert.Equal(30f, YGNodeLayoutGetWidth(root_child0));
        Assert.Equal(10f, YGNodeLayoutGetHeight(root_child0));
        Assert.Equal(30f, YGNodeLayoutGetLeft(root_child1));
        Assert.Equal(10f, YGNodeLayoutGetTop(root_child1));
        Assert.Equal(30f, YGNodeLayoutGetWidth(root_child1));
        Assert.Equal(20f, YGNodeLayoutGetHeight(root_child1));
        Assert.Equal(60f, YGNodeLayoutGetLeft(root_child2));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child2));
        Assert.Equal(30f, YGNodeLayoutGetWidth(root_child2));
        Assert.Equal(30f, YGNodeLayoutGetHeight(root_child2));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child3));
        Assert.Equal(30f, YGNodeLayoutGetTop(root_child3));
        Assert.Equal(30f, YGNodeLayoutGetWidth(root_child3));
        Assert.Equal(30f, YGNodeLayoutGetHeight(root_child3));
        YGNodeCalculateLayout(root, float.NaN, float.NaN, YGDirection.RTL);
        Assert.Equal(0f, YGNodeLayoutGetLeft(root));
        Assert.Equal(0f, YGNodeLayoutGetTop(root));
        Assert.Equal(100f, YGNodeLayoutGetWidth(root));
        Assert.Equal(60f, YGNodeLayoutGetHeight(root));
        Assert.Equal(70f, YGNodeLayoutGetLeft(root_child0));
        Assert.Equal(20f, YGNodeLayoutGetTop(root_child0));
        Assert.Equal(30f, YGNodeLayoutGetWidth(root_child0));
        Assert.Equal(10f, YGNodeLayoutGetHeight(root_child0));
        Assert.Equal(40f, YGNodeLayoutGetLeft(root_child1));
        Assert.Equal(10f, YGNodeLayoutGetTop(root_child1));
        Assert.Equal(30f, YGNodeLayoutGetWidth(root_child1));
        Assert.Equal(20f, YGNodeLayoutGetHeight(root_child1));
        Assert.Equal(10f, YGNodeLayoutGetLeft(root_child2));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child2));
        Assert.Equal(30f, YGNodeLayoutGetWidth(root_child2));
        Assert.Equal(30f, YGNodeLayoutGetHeight(root_child2));
        Assert.Equal(70f, YGNodeLayoutGetLeft(root_child3));
        Assert.Equal(30f, YGNodeLayoutGetTop(root_child3));
        Assert.Equal(30f, YGNodeLayoutGetWidth(root_child3));
        Assert.Equal(30f, YGNodeLayoutGetHeight(root_child3));
        YGNodeFreeRecursive(root);
        YGConfigFree(config);
    }

    [Fact]
    public void wrap_row_align_items_center()
    {
        var config = YGConfigNew();
        var root = YGNodeNewWithConfig(config);
        YGNodeStyleSetPositionType(root, YGPositionType.Absolute);
        YGNodeStyleSetWidth(root, 100);
        YGNodeStyleSetFlexDirection(root, YGFlexDirection.Row);
        YGNodeStyleSetFlexWrap(root, YGWrap.Wrap);
        YGNodeStyleSetAlignItems(root, YGAlign.Center);
        var root_child0 = YGNodeNewWithConfig(config);
        YGNodeStyleSetHeight(root_child0, 10);
        YGNodeStyleSetWidth(root_child0, 30);
        YGNodeInsertChild(root, root_child0, 0);
        var root_child1 = YGNodeNewWithConfig(config);
        YGNodeStyleSetHeight(root_child1, 20);
        YGNodeStyleSetWidth(root_child1, 30);
        YGNodeInsertChild(root, root_child1, 1);
        var root_child2 = YGNodeNewWithConfig(config);
        YGNodeStyleSetHeight(root_child2, 30);
        YGNodeStyleSetWidth(root_child2, 30);
        YGNodeInsertChild(root, root_child2, 2);
        var root_child3 = YGNodeNewWithConfig(config);
        YGNodeStyleSetHeight(root_child3, 30);
        YGNodeStyleSetWidth(root_child3, 30);
        YGNodeInsertChild(root, root_child3, 3);
        YGNodeCalculateLayout(root, float.NaN, float.NaN, YGDirection.LTR);
        Assert.Equal(0f, YGNodeLayoutGetLeft(root));
        Assert.Equal(0f, YGNodeLayoutGetTop(root));
        Assert.Equal(100f, YGNodeLayoutGetWidth(root));
        Assert.Equal(60f, YGNodeLayoutGetHeight(root));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child0));
        Assert.Equal(10f, YGNodeLayoutGetTop(root_child0));
        Assert.Equal(30f, YGNodeLayoutGetWidth(root_child0));
        Assert.Equal(10f, YGNodeLayoutGetHeight(root_child0));
        Assert.Equal(30f, YGNodeLayoutGetLeft(root_child1));
        Assert.Equal(5f, YGNodeLayoutGetTop(root_child1));
        Assert.Equal(30f, YGNodeLayoutGetWidth(root_child1));
        Assert.Equal(20f, YGNodeLayoutGetHeight(root_child1));
        Assert.Equal(60f, YGNodeLayoutGetLeft(root_child2));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child2));
        Assert.Equal(30f, YGNodeLayoutGetWidth(root_child2));
        Assert.Equal(30f, YGNodeLayoutGetHeight(root_child2));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child3));
        Assert.Equal(30f, YGNodeLayoutGetTop(root_child3));
        Assert.Equal(30f, YGNodeLayoutGetWidth(root_child3));
        Assert.Equal(30f, YGNodeLayoutGetHeight(root_child3));
        YGNodeCalculateLayout(root, float.NaN, float.NaN, YGDirection.RTL);
        Assert.Equal(0f, YGNodeLayoutGetLeft(root));
        Assert.Equal(0f, YGNodeLayoutGetTop(root));
        Assert.Equal(100f, YGNodeLayoutGetWidth(root));
        Assert.Equal(60f, YGNodeLayoutGetHeight(root));
        Assert.Equal(70f, YGNodeLayoutGetLeft(root_child0));
        Assert.Equal(10f, YGNodeLayoutGetTop(root_child0));
        Assert.Equal(30f, YGNodeLayoutGetWidth(root_child0));
        Assert.Equal(10f, YGNodeLayoutGetHeight(root_child0));
        Assert.Equal(40f, YGNodeLayoutGetLeft(root_child1));
        Assert.Equal(5f, YGNodeLayoutGetTop(root_child1));
        Assert.Equal(30f, YGNodeLayoutGetWidth(root_child1));
        Assert.Equal(20f, YGNodeLayoutGetHeight(root_child1));
        Assert.Equal(10f, YGNodeLayoutGetLeft(root_child2));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child2));
        Assert.Equal(30f, YGNodeLayoutGetWidth(root_child2));
        Assert.Equal(30f, YGNodeLayoutGetHeight(root_child2));
        Assert.Equal(70f, YGNodeLayoutGetLeft(root_child3));
        Assert.Equal(30f, YGNodeLayoutGetTop(root_child3));
        Assert.Equal(30f, YGNodeLayoutGetWidth(root_child3));
        Assert.Equal(30f, YGNodeLayoutGetHeight(root_child3));
        YGNodeFreeRecursive(root);
        YGConfigFree(config);
    }

    [Fact]
    public void flex_wrap_children_with_min_main_overriding_flex_basis()
    {
        var config = YGConfigNew();
        var root = YGNodeNewWithConfig(config);
        YGNodeStyleSetPositionType(root, YGPositionType.Absolute);
        YGNodeStyleSetWidth(root, 100);
        YGNodeStyleSetFlexWrap(root, YGWrap.Wrap);
        YGNodeStyleSetFlexDirection(root, YGFlexDirection.Row);
        var root_child0 = YGNodeNewWithConfig(config);
        YGNodeStyleSetFlexBasis(root_child0, 50);
        YGNodeStyleSetHeight(root_child0, 50);
        YGNodeStyleSetMinWidth(root_child0, 55);
        YGNodeInsertChild(root, root_child0, 0);
        var root_child1 = YGNodeNewWithConfig(config);
        YGNodeStyleSetFlexBasis(root_child1, 50);
        YGNodeStyleSetHeight(root_child1, 50);
        YGNodeStyleSetMinWidth(root_child1, 55);
        YGNodeInsertChild(root, root_child1, 1);
        YGNodeCalculateLayout(root, float.NaN, float.NaN, YGDirection.LTR);
        Assert.Equal(0f, YGNodeLayoutGetLeft(root));
        Assert.Equal(0f, YGNodeLayoutGetTop(root));
        Assert.Equal(100f, YGNodeLayoutGetWidth(root));
        Assert.Equal(100f, YGNodeLayoutGetHeight(root));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child0));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child0));
        Assert.Equal(55f, YGNodeLayoutGetWidth(root_child0));
        Assert.Equal(50f, YGNodeLayoutGetHeight(root_child0));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child1));
        Assert.Equal(50f, YGNodeLayoutGetTop(root_child1));
        Assert.Equal(55f, YGNodeLayoutGetWidth(root_child1));
        Assert.Equal(50f, YGNodeLayoutGetHeight(root_child1));
        YGNodeCalculateLayout(root, float.NaN, float.NaN, YGDirection.RTL);
        Assert.Equal(0f, YGNodeLayoutGetLeft(root));
        Assert.Equal(0f, YGNodeLayoutGetTop(root));
        Assert.Equal(100f, YGNodeLayoutGetWidth(root));
        Assert.Equal(100f, YGNodeLayoutGetHeight(root));
        Assert.Equal(45f, YGNodeLayoutGetLeft(root_child0));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child0));
        Assert.Equal(55f, YGNodeLayoutGetWidth(root_child0));
        Assert.Equal(50f, YGNodeLayoutGetHeight(root_child0));
        Assert.Equal(45f, YGNodeLayoutGetLeft(root_child1));
        Assert.Equal(50f, YGNodeLayoutGetTop(root_child1));
        Assert.Equal(55f, YGNodeLayoutGetWidth(root_child1));
        Assert.Equal(50f, YGNodeLayoutGetHeight(root_child1));
        YGNodeFreeRecursive(root);
        YGConfigFree(config);
    }

    [Fact]
    public void flex_wrap_wrap_to_child_height()
    {
        var config = YGConfigNew();
        var root = YGNodeNewWithConfig(config);
        YGNodeStyleSetPositionType(root, YGPositionType.Absolute);
        var root_child0 = YGNodeNewWithConfig(config);
        YGNodeStyleSetFlexDirection(root_child0, YGFlexDirection.Row);
        YGNodeStyleSetAlignItems(root_child0, YGAlign.FlexStart);
        YGNodeStyleSetFlexWrap(root_child0, YGWrap.Wrap);
        YGNodeInsertChild(root, root_child0, 0);
        var root_child0_child0 = YGNodeNewWithConfig(config);
        YGNodeStyleSetWidth(root_child0_child0, 100);
        YGNodeInsertChild(root_child0, root_child0_child0, 0);
        var root_child0_child0_child0 = YGNodeNewWithConfig(config);
        YGNodeStyleSetHeight(root_child0_child0_child0, 100);
        YGNodeStyleSetWidth(root_child0_child0_child0, 100);
        YGNodeInsertChild(root_child0_child0, root_child0_child0_child0, 0);
        var root_child1 = YGNodeNewWithConfig(config);
        YGNodeStyleSetWidth(root_child1, 100);
        YGNodeStyleSetHeight(root_child1, 100);
        YGNodeInsertChild(root, root_child1, 1);
        YGNodeCalculateLayout(root, float.NaN, float.NaN, YGDirection.LTR);
        Assert.Equal(0f, YGNodeLayoutGetLeft(root));
        Assert.Equal(0f, YGNodeLayoutGetTop(root));
        Assert.Equal(100f, YGNodeLayoutGetWidth(root));
        Assert.Equal(200f, YGNodeLayoutGetHeight(root));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child0));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child0));
        Assert.Equal(100f, YGNodeLayoutGetWidth(root_child0));
        Assert.Equal(100f, YGNodeLayoutGetHeight(root_child0));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child0_child0));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child0_child0));
        Assert.Equal(100f, YGNodeLayoutGetWidth(root_child0_child0));
        Assert.Equal(100f, YGNodeLayoutGetHeight(root_child0_child0));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child0_child0_child0));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child0_child0_child0));
        Assert.Equal(100f, YGNodeLayoutGetWidth(root_child0_child0_child0));
        Assert.Equal(100f, YGNodeLayoutGetHeight(root_child0_child0_child0));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child1));
        Assert.Equal(100f, YGNodeLayoutGetTop(root_child1));
        Assert.Equal(100f, YGNodeLayoutGetWidth(root_child1));
        Assert.Equal(100f, YGNodeLayoutGetHeight(root_child1));
        YGNodeCalculateLayout(root, float.NaN, float.NaN, YGDirection.RTL);
        Assert.Equal(0f, YGNodeLayoutGetLeft(root));
        Assert.Equal(0f, YGNodeLayoutGetTop(root));
        Assert.Equal(100f, YGNodeLayoutGetWidth(root));
        Assert.Equal(200f, YGNodeLayoutGetHeight(root));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child0));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child0));
        Assert.Equal(100f, YGNodeLayoutGetWidth(root_child0));
        Assert.Equal(100f, YGNodeLayoutGetHeight(root_child0));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child0_child0));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child0_child0));
        Assert.Equal(100f, YGNodeLayoutGetWidth(root_child0_child0));
        Assert.Equal(100f, YGNodeLayoutGetHeight(root_child0_child0));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child0_child0_child0));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child0_child0_child0));
        Assert.Equal(100f, YGNodeLayoutGetWidth(root_child0_child0_child0));
        Assert.Equal(100f, YGNodeLayoutGetHeight(root_child0_child0_child0));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child1));
        Assert.Equal(100f, YGNodeLayoutGetTop(root_child1));
        Assert.Equal(100f, YGNodeLayoutGetWidth(root_child1));
        Assert.Equal(100f, YGNodeLayoutGetHeight(root_child1));
        YGNodeFreeRecursive(root);
        YGConfigFree(config);
    }

    [Fact]
    public void flex_wrap_align_stretch_fits_one_row()
    {
        var config = YGConfigNew();
        var root = YGNodeNewWithConfig(config);
        YGNodeStyleSetPositionType(root, YGPositionType.Absolute);
        YGNodeStyleSetWidth(root, 150);
        YGNodeStyleSetHeight(root, 100);
        YGNodeStyleSetFlexWrap(root, YGWrap.Wrap);
        YGNodeStyleSetFlexDirection(root, YGFlexDirection.Row);
        var root_child0 = YGNodeNewWithConfig(config);
        YGNodeStyleSetWidth(root_child0, 50);
        YGNodeInsertChild(root, root_child0, 0);
        var root_child1 = YGNodeNewWithConfig(config);
        YGNodeStyleSetWidth(root_child1, 50);
        YGNodeInsertChild(root, root_child1, 1);
        YGNodeCalculateLayout(root, float.NaN, float.NaN, YGDirection.LTR);
        Assert.Equal(0f, YGNodeLayoutGetLeft(root));
        Assert.Equal(0f, YGNodeLayoutGetTop(root));
        Assert.Equal(150f, YGNodeLayoutGetWidth(root));
        Assert.Equal(100f, YGNodeLayoutGetHeight(root));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child0));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child0));
        Assert.Equal(50f, YGNodeLayoutGetWidth(root_child0));
        Assert.Equal(0f, YGNodeLayoutGetHeight(root_child0));
        Assert.Equal(50f, YGNodeLayoutGetLeft(root_child1));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child1));
        Assert.Equal(50f, YGNodeLayoutGetWidth(root_child1));
        Assert.Equal(0f, YGNodeLayoutGetHeight(root_child1));
        YGNodeCalculateLayout(root, float.NaN, float.NaN, YGDirection.RTL);
        Assert.Equal(0f, YGNodeLayoutGetLeft(root));
        Assert.Equal(0f, YGNodeLayoutGetTop(root));
        Assert.Equal(150f, YGNodeLayoutGetWidth(root));
        Assert.Equal(100f, YGNodeLayoutGetHeight(root));
        Assert.Equal(100f, YGNodeLayoutGetLeft(root_child0));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child0));
        Assert.Equal(50f, YGNodeLayoutGetWidth(root_child0));
        Assert.Equal(0f, YGNodeLayoutGetHeight(root_child0));
        Assert.Equal(50f, YGNodeLayoutGetLeft(root_child1));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child1));
        Assert.Equal(50f, YGNodeLayoutGetWidth(root_child1));
        Assert.Equal(0f, YGNodeLayoutGetHeight(root_child1));
        YGNodeFreeRecursive(root);
        YGConfigFree(config);
    }

    [Fact]
    public void wrap_reverse_row_align_content_flex_start()
    {
        var config = YGConfigNew();
        var root = YGNodeNewWithConfig(config);
        YGNodeStyleSetPositionType(root, YGPositionType.Absolute);
        YGNodeStyleSetWidth(root, 100);
        YGNodeStyleSetFlexDirection(root, YGFlexDirection.Row);
        YGNodeStyleSetFlexWrap(root, YGWrap.WrapReverse);
        var root_child0 = YGNodeNewWithConfig(config);
        YGNodeStyleSetHeight(root_child0, 10);
        YGNodeStyleSetWidth(root_child0, 30);
        YGNodeInsertChild(root, root_child0, 0);
        var root_child1 = YGNodeNewWithConfig(config);
        YGNodeStyleSetHeight(root_child1, 20);
        YGNodeStyleSetWidth(root_child1, 30);
        YGNodeInsertChild(root, root_child1, 1);
        var root_child2 = YGNodeNewWithConfig(config);
        YGNodeStyleSetHeight(root_child2, 30);
        YGNodeStyleSetWidth(root_child2, 30);
        YGNodeInsertChild(root, root_child2, 2);
        var root_child3 = YGNodeNewWithConfig(config);
        YGNodeStyleSetHeight(root_child3, 40);
        YGNodeStyleSetWidth(root_child3, 30);
        YGNodeInsertChild(root, root_child3, 3);
        var root_child4 = YGNodeNewWithConfig(config);
        YGNodeStyleSetHeight(root_child4, 50);
        YGNodeStyleSetWidth(root_child4, 30);
        YGNodeInsertChild(root, root_child4, 4);
        YGNodeCalculateLayout(root, float.NaN, float.NaN, YGDirection.LTR);
        Assert.Equal(0f, YGNodeLayoutGetLeft(root));
        Assert.Equal(0f, YGNodeLayoutGetTop(root));
        Assert.Equal(100f, YGNodeLayoutGetWidth(root));
        Assert.Equal(80f, YGNodeLayoutGetHeight(root));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child0));
        Assert.Equal(70f, YGNodeLayoutGetTop(root_child0));
        Assert.Equal(30f, YGNodeLayoutGetWidth(root_child0));
        Assert.Equal(10f, YGNodeLayoutGetHeight(root_child0));
        Assert.Equal(30f, YGNodeLayoutGetLeft(root_child1));
        Assert.Equal(60f, YGNodeLayoutGetTop(root_child1));
        Assert.Equal(30f, YGNodeLayoutGetWidth(root_child1));
        Assert.Equal(20f, YGNodeLayoutGetHeight(root_child1));
        Assert.Equal(60f, YGNodeLayoutGetLeft(root_child2));
        Assert.Equal(50f, YGNodeLayoutGetTop(root_child2));
        Assert.Equal(30f, YGNodeLayoutGetWidth(root_child2));
        Assert.Equal(30f, YGNodeLayoutGetHeight(root_child2));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child3));
        Assert.Equal(10f, YGNodeLayoutGetTop(root_child3));
        Assert.Equal(30f, YGNodeLayoutGetWidth(root_child3));
        Assert.Equal(40f, YGNodeLayoutGetHeight(root_child3));
        Assert.Equal(30f, YGNodeLayoutGetLeft(root_child4));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child4));
        Assert.Equal(30f, YGNodeLayoutGetWidth(root_child4));
        Assert.Equal(50f, YGNodeLayoutGetHeight(root_child4));
        YGNodeCalculateLayout(root, float.NaN, float.NaN, YGDirection.RTL);
        Assert.Equal(0f, YGNodeLayoutGetLeft(root));
        Assert.Equal(0f, YGNodeLayoutGetTop(root));
        Assert.Equal(100f, YGNodeLayoutGetWidth(root));
        Assert.Equal(80f, YGNodeLayoutGetHeight(root));
        Assert.Equal(70f, YGNodeLayoutGetLeft(root_child0));
        Assert.Equal(70f, YGNodeLayoutGetTop(root_child0));
        Assert.Equal(30f, YGNodeLayoutGetWidth(root_child0));
        Assert.Equal(10f, YGNodeLayoutGetHeight(root_child0));
        Assert.Equal(40f, YGNodeLayoutGetLeft(root_child1));
        Assert.Equal(60f, YGNodeLayoutGetTop(root_child1));
        Assert.Equal(30f, YGNodeLayoutGetWidth(root_child1));
        Assert.Equal(20f, YGNodeLayoutGetHeight(root_child1));
        Assert.Equal(10f, YGNodeLayoutGetLeft(root_child2));
        Assert.Equal(50f, YGNodeLayoutGetTop(root_child2));
        Assert.Equal(30f, YGNodeLayoutGetWidth(root_child2));
        Assert.Equal(30f, YGNodeLayoutGetHeight(root_child2));
        Assert.Equal(70f, YGNodeLayoutGetLeft(root_child3));
        Assert.Equal(10f, YGNodeLayoutGetTop(root_child3));
        Assert.Equal(30f, YGNodeLayoutGetWidth(root_child3));
        Assert.Equal(40f, YGNodeLayoutGetHeight(root_child3));
        Assert.Equal(40f, YGNodeLayoutGetLeft(root_child4));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child4));
        Assert.Equal(30f, YGNodeLayoutGetWidth(root_child4));
        Assert.Equal(50f, YGNodeLayoutGetHeight(root_child4));
        YGNodeFreeRecursive(root);
        YGConfigFree(config);
    }

    [Fact]
    public void wrap_reverse_row_align_content_center()
    {
        var config = YGConfigNew();
        var root = YGNodeNewWithConfig(config);
        YGNodeStyleSetPositionType(root, YGPositionType.Absolute);
        YGNodeStyleSetWidth(root, 100);
        YGNodeStyleSetFlexDirection(root, YGFlexDirection.Row);
        YGNodeStyleSetFlexWrap(root, YGWrap.WrapReverse);
        YGNodeStyleSetAlignContent(root, YGAlign.Center);
        var root_child0 = YGNodeNewWithConfig(config);
        YGNodeStyleSetHeight(root_child0, 10);
        YGNodeStyleSetWidth(root_child0, 30);
        YGNodeInsertChild(root, root_child0, 0);
        var root_child1 = YGNodeNewWithConfig(config);
        YGNodeStyleSetHeight(root_child1, 20);
        YGNodeStyleSetWidth(root_child1, 30);
        YGNodeInsertChild(root, root_child1, 1);
        var root_child2 = YGNodeNewWithConfig(config);
        YGNodeStyleSetHeight(root_child2, 30);
        YGNodeStyleSetWidth(root_child2, 30);
        YGNodeInsertChild(root, root_child2, 2);
        var root_child3 = YGNodeNewWithConfig(config);
        YGNodeStyleSetHeight(root_child3, 40);
        YGNodeStyleSetWidth(root_child3, 30);
        YGNodeInsertChild(root, root_child3, 3);
        var root_child4 = YGNodeNewWithConfig(config);
        YGNodeStyleSetHeight(root_child4, 50);
        YGNodeStyleSetWidth(root_child4, 30);
        YGNodeInsertChild(root, root_child4, 4);
        YGNodeCalculateLayout(root, float.NaN, float.NaN, YGDirection.LTR);
        Assert.Equal(0f, YGNodeLayoutGetLeft(root));
        Assert.Equal(0f, YGNodeLayoutGetTop(root));
        Assert.Equal(100f, YGNodeLayoutGetWidth(root));
        Assert.Equal(80f, YGNodeLayoutGetHeight(root));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child0));
        Assert.Equal(70f, YGNodeLayoutGetTop(root_child0));
        Assert.Equal(30f, YGNodeLayoutGetWidth(root_child0));
        Assert.Equal(10f, YGNodeLayoutGetHeight(root_child0));
        Assert.Equal(30f, YGNodeLayoutGetLeft(root_child1));
        Assert.Equal(60f, YGNodeLayoutGetTop(root_child1));
        Assert.Equal(30f, YGNodeLayoutGetWidth(root_child1));
        Assert.Equal(20f, YGNodeLayoutGetHeight(root_child1));
        Assert.Equal(60f, YGNodeLayoutGetLeft(root_child2));
        Assert.Equal(50f, YGNodeLayoutGetTop(root_child2));
        Assert.Equal(30f, YGNodeLayoutGetWidth(root_child2));
        Assert.Equal(30f, YGNodeLayoutGetHeight(root_child2));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child3));
        Assert.Equal(10f, YGNodeLayoutGetTop(root_child3));
        Assert.Equal(30f, YGNodeLayoutGetWidth(root_child3));
        Assert.Equal(40f, YGNodeLayoutGetHeight(root_child3));
        Assert.Equal(30f, YGNodeLayoutGetLeft(root_child4));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child4));
        Assert.Equal(30f, YGNodeLayoutGetWidth(root_child4));
        Assert.Equal(50f, YGNodeLayoutGetHeight(root_child4));
        YGNodeCalculateLayout(root, float.NaN, float.NaN, YGDirection.RTL);
        Assert.Equal(0f, YGNodeLayoutGetLeft(root));
        Assert.Equal(0f, YGNodeLayoutGetTop(root));
        Assert.Equal(100f, YGNodeLayoutGetWidth(root));
        Assert.Equal(80f, YGNodeLayoutGetHeight(root));
        Assert.Equal(70f, YGNodeLayoutGetLeft(root_child0));
        Assert.Equal(70f, YGNodeLayoutGetTop(root_child0));
        Assert.Equal(30f, YGNodeLayoutGetWidth(root_child0));
        Assert.Equal(10f, YGNodeLayoutGetHeight(root_child0));
        Assert.Equal(40f, YGNodeLayoutGetLeft(root_child1));
        Assert.Equal(60f, YGNodeLayoutGetTop(root_child1));
        Assert.Equal(30f, YGNodeLayoutGetWidth(root_child1));
        Assert.Equal(20f, YGNodeLayoutGetHeight(root_child1));
        Assert.Equal(10f, YGNodeLayoutGetLeft(root_child2));
        Assert.Equal(50f, YGNodeLayoutGetTop(root_child2));
        Assert.Equal(30f, YGNodeLayoutGetWidth(root_child2));
        Assert.Equal(30f, YGNodeLayoutGetHeight(root_child2));
        Assert.Equal(70f, YGNodeLayoutGetLeft(root_child3));
        Assert.Equal(10f, YGNodeLayoutGetTop(root_child3));
        Assert.Equal(30f, YGNodeLayoutGetWidth(root_child3));
        Assert.Equal(40f, YGNodeLayoutGetHeight(root_child3));
        Assert.Equal(40f, YGNodeLayoutGetLeft(root_child4));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child4));
        Assert.Equal(30f, YGNodeLayoutGetWidth(root_child4));
        Assert.Equal(50f, YGNodeLayoutGetHeight(root_child4));
        YGNodeFreeRecursive(root);
        YGConfigFree(config);
    }

    [Fact]
    public void wrap_reverse_row_single_line_different_size()
    {
        var config = YGConfigNew();
        var root = YGNodeNewWithConfig(config);
        YGNodeStyleSetPositionType(root, YGPositionType.Absolute);
        YGNodeStyleSetWidth(root, 300);
        YGNodeStyleSetFlexDirection(root, YGFlexDirection.Row);
        YGNodeStyleSetFlexWrap(root, YGWrap.WrapReverse);
        var root_child0 = YGNodeNewWithConfig(config);
        YGNodeStyleSetHeight(root_child0, 10);
        YGNodeStyleSetWidth(root_child0, 30);
        YGNodeInsertChild(root, root_child0, 0);
        var root_child1 = YGNodeNewWithConfig(config);
        YGNodeStyleSetHeight(root_child1, 20);
        YGNodeStyleSetWidth(root_child1, 30);
        YGNodeInsertChild(root, root_child1, 1);
        var root_child2 = YGNodeNewWithConfig(config);
        YGNodeStyleSetHeight(root_child2, 30);
        YGNodeStyleSetWidth(root_child2, 30);
        YGNodeInsertChild(root, root_child2, 2);
        var root_child3 = YGNodeNewWithConfig(config);
        YGNodeStyleSetHeight(root_child3, 40);
        YGNodeStyleSetWidth(root_child3, 30);
        YGNodeInsertChild(root, root_child3, 3);
        var root_child4 = YGNodeNewWithConfig(config);
        YGNodeStyleSetHeight(root_child4, 50);
        YGNodeStyleSetWidth(root_child4, 30);
        YGNodeInsertChild(root, root_child4, 4);
        YGNodeCalculateLayout(root, float.NaN, float.NaN, YGDirection.LTR);
        Assert.Equal(0f, YGNodeLayoutGetLeft(root));
        Assert.Equal(0f, YGNodeLayoutGetTop(root));
        Assert.Equal(300f, YGNodeLayoutGetWidth(root));
        Assert.Equal(50f, YGNodeLayoutGetHeight(root));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child0));
        Assert.Equal(40f, YGNodeLayoutGetTop(root_child0));
        Assert.Equal(30f, YGNodeLayoutGetWidth(root_child0));
        Assert.Equal(10f, YGNodeLayoutGetHeight(root_child0));
        Assert.Equal(30f, YGNodeLayoutGetLeft(root_child1));
        Assert.Equal(30f, YGNodeLayoutGetTop(root_child1));
        Assert.Equal(30f, YGNodeLayoutGetWidth(root_child1));
        Assert.Equal(20f, YGNodeLayoutGetHeight(root_child1));
        Assert.Equal(60f, YGNodeLayoutGetLeft(root_child2));
        Assert.Equal(20f, YGNodeLayoutGetTop(root_child2));
        Assert.Equal(30f, YGNodeLayoutGetWidth(root_child2));
        Assert.Equal(30f, YGNodeLayoutGetHeight(root_child2));
        Assert.Equal(90f, YGNodeLayoutGetLeft(root_child3));
        Assert.Equal(10f, YGNodeLayoutGetTop(root_child3));
        Assert.Equal(30f, YGNodeLayoutGetWidth(root_child3));
        Assert.Equal(40f, YGNodeLayoutGetHeight(root_child3));
        Assert.Equal(120f, YGNodeLayoutGetLeft(root_child4));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child4));
        Assert.Equal(30f, YGNodeLayoutGetWidth(root_child4));
        Assert.Equal(50f, YGNodeLayoutGetHeight(root_child4));
        YGNodeCalculateLayout(root, float.NaN, float.NaN, YGDirection.RTL);
        Assert.Equal(0f, YGNodeLayoutGetLeft(root));
        Assert.Equal(0f, YGNodeLayoutGetTop(root));
        Assert.Equal(300f, YGNodeLayoutGetWidth(root));
        Assert.Equal(50f, YGNodeLayoutGetHeight(root));
        Assert.Equal(270f, YGNodeLayoutGetLeft(root_child0));
        Assert.Equal(40f, YGNodeLayoutGetTop(root_child0));
        Assert.Equal(30f, YGNodeLayoutGetWidth(root_child0));
        Assert.Equal(10f, YGNodeLayoutGetHeight(root_child0));
        Assert.Equal(240f, YGNodeLayoutGetLeft(root_child1));
        Assert.Equal(30f, YGNodeLayoutGetTop(root_child1));
        Assert.Equal(30f, YGNodeLayoutGetWidth(root_child1));
        Assert.Equal(20f, YGNodeLayoutGetHeight(root_child1));
        Assert.Equal(210f, YGNodeLayoutGetLeft(root_child2));
        Assert.Equal(20f, YGNodeLayoutGetTop(root_child2));
        Assert.Equal(30f, YGNodeLayoutGetWidth(root_child2));
        Assert.Equal(30f, YGNodeLayoutGetHeight(root_child2));
        Assert.Equal(180f, YGNodeLayoutGetLeft(root_child3));
        Assert.Equal(10f, YGNodeLayoutGetTop(root_child3));
        Assert.Equal(30f, YGNodeLayoutGetWidth(root_child3));
        Assert.Equal(40f, YGNodeLayoutGetHeight(root_child3));
        Assert.Equal(150f, YGNodeLayoutGetLeft(root_child4));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child4));
        Assert.Equal(30f, YGNodeLayoutGetWidth(root_child4));
        Assert.Equal(50f, YGNodeLayoutGetHeight(root_child4));
        YGNodeFreeRecursive(root);
        YGConfigFree(config);
    }

    [Fact]
    public void wrap_reverse_row_align_content_stretch()
    {
        var config = YGConfigNew();
        var root = YGNodeNewWithConfig(config);
        YGNodeStyleSetPositionType(root, YGPositionType.Absolute);
        YGNodeStyleSetWidth(root, 100);
        YGNodeStyleSetFlexDirection(root, YGFlexDirection.Row);
        YGNodeStyleSetFlexWrap(root, YGWrap.WrapReverse);
        YGNodeStyleSetAlignContent(root, YGAlign.Stretch);
        var root_child0 = YGNodeNewWithConfig(config);
        YGNodeStyleSetHeight(root_child0, 10);
        YGNodeStyleSetWidth(root_child0, 30);
        YGNodeInsertChild(root, root_child0, 0);
        var root_child1 = YGNodeNewWithConfig(config);
        YGNodeStyleSetHeight(root_child1, 20);
        YGNodeStyleSetWidth(root_child1, 30);
        YGNodeInsertChild(root, root_child1, 1);
        var root_child2 = YGNodeNewWithConfig(config);
        YGNodeStyleSetHeight(root_child2, 30);
        YGNodeStyleSetWidth(root_child2, 30);
        YGNodeInsertChild(root, root_child2, 2);
        var root_child3 = YGNodeNewWithConfig(config);
        YGNodeStyleSetHeight(root_child3, 40);
        YGNodeStyleSetWidth(root_child3, 30);
        YGNodeInsertChild(root, root_child3, 3);
        var root_child4 = YGNodeNewWithConfig(config);
        YGNodeStyleSetHeight(root_child4, 50);
        YGNodeStyleSetWidth(root_child4, 30);
        YGNodeInsertChild(root, root_child4, 4);
        YGNodeCalculateLayout(root, float.NaN, float.NaN, YGDirection.LTR);
        Assert.Equal(0f, YGNodeLayoutGetLeft(root));
        Assert.Equal(0f, YGNodeLayoutGetTop(root));
        Assert.Equal(100f, YGNodeLayoutGetWidth(root));
        Assert.Equal(80f, YGNodeLayoutGetHeight(root));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child0));
        Assert.Equal(70f, YGNodeLayoutGetTop(root_child0));
        Assert.Equal(30f, YGNodeLayoutGetWidth(root_child0));
        Assert.Equal(10f, YGNodeLayoutGetHeight(root_child0));
        Assert.Equal(30f, YGNodeLayoutGetLeft(root_child1));
        Assert.Equal(60f, YGNodeLayoutGetTop(root_child1));
        Assert.Equal(30f, YGNodeLayoutGetWidth(root_child1));
        Assert.Equal(20f, YGNodeLayoutGetHeight(root_child1));
        Assert.Equal(60f, YGNodeLayoutGetLeft(root_child2));
        Assert.Equal(50f, YGNodeLayoutGetTop(root_child2));
        Assert.Equal(30f, YGNodeLayoutGetWidth(root_child2));
        Assert.Equal(30f, YGNodeLayoutGetHeight(root_child2));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child3));
        Assert.Equal(10f, YGNodeLayoutGetTop(root_child3));
        Assert.Equal(30f, YGNodeLayoutGetWidth(root_child3));
        Assert.Equal(40f, YGNodeLayoutGetHeight(root_child3));
        Assert.Equal(30f, YGNodeLayoutGetLeft(root_child4));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child4));
        Assert.Equal(30f, YGNodeLayoutGetWidth(root_child4));
        Assert.Equal(50f, YGNodeLayoutGetHeight(root_child4));
        YGNodeCalculateLayout(root, float.NaN, float.NaN, YGDirection.RTL);
        Assert.Equal(0f, YGNodeLayoutGetLeft(root));
        Assert.Equal(0f, YGNodeLayoutGetTop(root));
        Assert.Equal(100f, YGNodeLayoutGetWidth(root));
        Assert.Equal(80f, YGNodeLayoutGetHeight(root));
        Assert.Equal(70f, YGNodeLayoutGetLeft(root_child0));
        Assert.Equal(70f, YGNodeLayoutGetTop(root_child0));
        Assert.Equal(30f, YGNodeLayoutGetWidth(root_child0));
        Assert.Equal(10f, YGNodeLayoutGetHeight(root_child0));
        Assert.Equal(40f, YGNodeLayoutGetLeft(root_child1));
        Assert.Equal(60f, YGNodeLayoutGetTop(root_child1));
        Assert.Equal(30f, YGNodeLayoutGetWidth(root_child1));
        Assert.Equal(20f, YGNodeLayoutGetHeight(root_child1));
        Assert.Equal(10f, YGNodeLayoutGetLeft(root_child2));
        Assert.Equal(50f, YGNodeLayoutGetTop(root_child2));
        Assert.Equal(30f, YGNodeLayoutGetWidth(root_child2));
        Assert.Equal(30f, YGNodeLayoutGetHeight(root_child2));
        Assert.Equal(70f, YGNodeLayoutGetLeft(root_child3));
        Assert.Equal(10f, YGNodeLayoutGetTop(root_child3));
        Assert.Equal(30f, YGNodeLayoutGetWidth(root_child3));
        Assert.Equal(40f, YGNodeLayoutGetHeight(root_child3));
        Assert.Equal(40f, YGNodeLayoutGetLeft(root_child4));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child4));
        Assert.Equal(30f, YGNodeLayoutGetWidth(root_child4));
        Assert.Equal(50f, YGNodeLayoutGetHeight(root_child4));
        YGNodeFreeRecursive(root);
        YGConfigFree(config);
    }

    [Fact]
    public void wrap_reverse_row_align_content_space_around()
    {
        var config = YGConfigNew();
        var root = YGNodeNewWithConfig(config);
        YGNodeStyleSetPositionType(root, YGPositionType.Absolute);
        YGNodeStyleSetWidth(root, 100);
        YGNodeStyleSetFlexDirection(root, YGFlexDirection.Row);
        YGNodeStyleSetFlexWrap(root, YGWrap.WrapReverse);
        YGNodeStyleSetAlignContent(root, YGAlign.SpaceAround);
        var root_child0 = YGNodeNewWithConfig(config);
        YGNodeStyleSetHeight(root_child0, 10);
        YGNodeStyleSetWidth(root_child0, 30);
        YGNodeInsertChild(root, root_child0, 0);
        var root_child1 = YGNodeNewWithConfig(config);
        YGNodeStyleSetHeight(root_child1, 20);
        YGNodeStyleSetWidth(root_child1, 30);
        YGNodeInsertChild(root, root_child1, 1);
        var root_child2 = YGNodeNewWithConfig(config);
        YGNodeStyleSetHeight(root_child2, 30);
        YGNodeStyleSetWidth(root_child2, 30);
        YGNodeInsertChild(root, root_child2, 2);
        var root_child3 = YGNodeNewWithConfig(config);
        YGNodeStyleSetHeight(root_child3, 40);
        YGNodeStyleSetWidth(root_child3, 30);
        YGNodeInsertChild(root, root_child3, 3);
        var root_child4 = YGNodeNewWithConfig(config);
        YGNodeStyleSetHeight(root_child4, 50);
        YGNodeStyleSetWidth(root_child4, 30);
        YGNodeInsertChild(root, root_child4, 4);
        YGNodeCalculateLayout(root, float.NaN, float.NaN, YGDirection.LTR);
        Assert.Equal(0f, YGNodeLayoutGetLeft(root));
        Assert.Equal(0f, YGNodeLayoutGetTop(root));
        Assert.Equal(100f, YGNodeLayoutGetWidth(root));
        Assert.Equal(80f, YGNodeLayoutGetHeight(root));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child0));
        Assert.Equal(70f, YGNodeLayoutGetTop(root_child0));
        Assert.Equal(30f, YGNodeLayoutGetWidth(root_child0));
        Assert.Equal(10f, YGNodeLayoutGetHeight(root_child0));
        Assert.Equal(30f, YGNodeLayoutGetLeft(root_child1));
        Assert.Equal(60f, YGNodeLayoutGetTop(root_child1));
        Assert.Equal(30f, YGNodeLayoutGetWidth(root_child1));
        Assert.Equal(20f, YGNodeLayoutGetHeight(root_child1));
        Assert.Equal(60f, YGNodeLayoutGetLeft(root_child2));
        Assert.Equal(50f, YGNodeLayoutGetTop(root_child2));
        Assert.Equal(30f, YGNodeLayoutGetWidth(root_child2));
        Assert.Equal(30f, YGNodeLayoutGetHeight(root_child2));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child3));
        Assert.Equal(10f, YGNodeLayoutGetTop(root_child3));
        Assert.Equal(30f, YGNodeLayoutGetWidth(root_child3));
        Assert.Equal(40f, YGNodeLayoutGetHeight(root_child3));
        Assert.Equal(30f, YGNodeLayoutGetLeft(root_child4));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child4));
        Assert.Equal(30f, YGNodeLayoutGetWidth(root_child4));
        Assert.Equal(50f, YGNodeLayoutGetHeight(root_child4));
        YGNodeCalculateLayout(root, float.NaN, float.NaN, YGDirection.RTL);
        Assert.Equal(0f, YGNodeLayoutGetLeft(root));
        Assert.Equal(0f, YGNodeLayoutGetTop(root));
        Assert.Equal(100f, YGNodeLayoutGetWidth(root));
        Assert.Equal(80f, YGNodeLayoutGetHeight(root));
        Assert.Equal(70f, YGNodeLayoutGetLeft(root_child0));
        Assert.Equal(70f, YGNodeLayoutGetTop(root_child0));
        Assert.Equal(30f, YGNodeLayoutGetWidth(root_child0));
        Assert.Equal(10f, YGNodeLayoutGetHeight(root_child0));
        Assert.Equal(40f, YGNodeLayoutGetLeft(root_child1));
        Assert.Equal(60f, YGNodeLayoutGetTop(root_child1));
        Assert.Equal(30f, YGNodeLayoutGetWidth(root_child1));
        Assert.Equal(20f, YGNodeLayoutGetHeight(root_child1));
        Assert.Equal(10f, YGNodeLayoutGetLeft(root_child2));
        Assert.Equal(50f, YGNodeLayoutGetTop(root_child2));
        Assert.Equal(30f, YGNodeLayoutGetWidth(root_child2));
        Assert.Equal(30f, YGNodeLayoutGetHeight(root_child2));
        Assert.Equal(70f, YGNodeLayoutGetLeft(root_child3));
        Assert.Equal(10f, YGNodeLayoutGetTop(root_child3));
        Assert.Equal(30f, YGNodeLayoutGetWidth(root_child3));
        Assert.Equal(40f, YGNodeLayoutGetHeight(root_child3));
        Assert.Equal(40f, YGNodeLayoutGetLeft(root_child4));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child4));
        Assert.Equal(30f, YGNodeLayoutGetWidth(root_child4));
        Assert.Equal(50f, YGNodeLayoutGetHeight(root_child4));
        YGNodeFreeRecursive(root);
        YGConfigFree(config);
    }

    [Fact]
    public void wrap_reverse_column_fixed_size()
    {
        var config = YGConfigNew();
        var root = YGNodeNewWithConfig(config);
        YGNodeStyleSetPositionType(root, YGPositionType.Absolute);
        YGNodeStyleSetWidth(root, 200);
        YGNodeStyleSetHeight(root, 100);
        YGNodeStyleSetFlexWrap(root, YGWrap.WrapReverse);
        YGNodeStyleSetAlignItems(root, YGAlign.Center);
        var root_child0 = YGNodeNewWithConfig(config);
        YGNodeStyleSetHeight(root_child0, 10);
        YGNodeStyleSetWidth(root_child0, 30);
        YGNodeInsertChild(root, root_child0, 0);
        var root_child1 = YGNodeNewWithConfig(config);
        YGNodeStyleSetHeight(root_child1, 20);
        YGNodeStyleSetWidth(root_child1, 30);
        YGNodeInsertChild(root, root_child1, 1);
        var root_child2 = YGNodeNewWithConfig(config);
        YGNodeStyleSetHeight(root_child2, 30);
        YGNodeStyleSetWidth(root_child2, 30);
        YGNodeInsertChild(root, root_child2, 2);
        var root_child3 = YGNodeNewWithConfig(config);
        YGNodeStyleSetHeight(root_child3, 40);
        YGNodeStyleSetWidth(root_child3, 30);
        YGNodeInsertChild(root, root_child3, 3);
        var root_child4 = YGNodeNewWithConfig(config);
        YGNodeStyleSetHeight(root_child4, 50);
        YGNodeStyleSetWidth(root_child4, 30);
        YGNodeInsertChild(root, root_child4, 4);
        YGNodeCalculateLayout(root, float.NaN, float.NaN, YGDirection.LTR);
        Assert.Equal(0f, YGNodeLayoutGetLeft(root));
        Assert.Equal(0f, YGNodeLayoutGetTop(root));
        Assert.Equal(200f, YGNodeLayoutGetWidth(root));
        Assert.Equal(100f, YGNodeLayoutGetHeight(root));
        Assert.Equal(170f, YGNodeLayoutGetLeft(root_child0));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child0));
        Assert.Equal(30f, YGNodeLayoutGetWidth(root_child0));
        Assert.Equal(10f, YGNodeLayoutGetHeight(root_child0));
        Assert.Equal(170f, YGNodeLayoutGetLeft(root_child1));
        Assert.Equal(10f, YGNodeLayoutGetTop(root_child1));
        Assert.Equal(30f, YGNodeLayoutGetWidth(root_child1));
        Assert.Equal(20f, YGNodeLayoutGetHeight(root_child1));
        Assert.Equal(170f, YGNodeLayoutGetLeft(root_child2));
        Assert.Equal(30f, YGNodeLayoutGetTop(root_child2));
        Assert.Equal(30f, YGNodeLayoutGetWidth(root_child2));
        Assert.Equal(30f, YGNodeLayoutGetHeight(root_child2));
        Assert.Equal(170f, YGNodeLayoutGetLeft(root_child3));
        Assert.Equal(60f, YGNodeLayoutGetTop(root_child3));
        Assert.Equal(30f, YGNodeLayoutGetWidth(root_child3));
        Assert.Equal(40f, YGNodeLayoutGetHeight(root_child3));
        Assert.Equal(140f, YGNodeLayoutGetLeft(root_child4));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child4));
        Assert.Equal(30f, YGNodeLayoutGetWidth(root_child4));
        Assert.Equal(50f, YGNodeLayoutGetHeight(root_child4));
        YGNodeCalculateLayout(root, float.NaN, float.NaN, YGDirection.RTL);
        Assert.Equal(0f, YGNodeLayoutGetLeft(root));
        Assert.Equal(0f, YGNodeLayoutGetTop(root));
        Assert.Equal(200f, YGNodeLayoutGetWidth(root));
        Assert.Equal(100f, YGNodeLayoutGetHeight(root));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child0));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child0));
        Assert.Equal(30f, YGNodeLayoutGetWidth(root_child0));
        Assert.Equal(10f, YGNodeLayoutGetHeight(root_child0));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child1));
        Assert.Equal(10f, YGNodeLayoutGetTop(root_child1));
        Assert.Equal(30f, YGNodeLayoutGetWidth(root_child1));
        Assert.Equal(20f, YGNodeLayoutGetHeight(root_child1));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child2));
        Assert.Equal(30f, YGNodeLayoutGetTop(root_child2));
        Assert.Equal(30f, YGNodeLayoutGetWidth(root_child2));
        Assert.Equal(30f, YGNodeLayoutGetHeight(root_child2));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child3));
        Assert.Equal(60f, YGNodeLayoutGetTop(root_child3));
        Assert.Equal(30f, YGNodeLayoutGetWidth(root_child3));
        Assert.Equal(40f, YGNodeLayoutGetHeight(root_child3));
        Assert.Equal(30f, YGNodeLayoutGetLeft(root_child4));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child4));
        Assert.Equal(30f, YGNodeLayoutGetWidth(root_child4));
        Assert.Equal(50f, YGNodeLayoutGetHeight(root_child4));
        YGNodeFreeRecursive(root);
        YGConfigFree(config);
    }

    [Fact]
    public void wrapped_row_within_align_items_center()
    {
        var config = YGConfigNew();
        var root = YGNodeNewWithConfig(config);
        YGNodeStyleSetPositionType(root, YGPositionType.Absolute);
        YGNodeStyleSetWidth(root, 200);
        YGNodeStyleSetHeight(root, 200);
        YGNodeStyleSetAlignItems(root, YGAlign.Center);
        var root_child0 = YGNodeNewWithConfig(config);
        YGNodeStyleSetFlexDirection(root_child0, YGFlexDirection.Row);
        YGNodeStyleSetFlexWrap(root_child0, YGWrap.Wrap);
        YGNodeInsertChild(root, root_child0, 0);
        var root_child0_child0 = YGNodeNewWithConfig(config);
        YGNodeStyleSetWidth(root_child0_child0, 150);
        YGNodeStyleSetHeight(root_child0_child0, 80);
        YGNodeInsertChild(root_child0, root_child0_child0, 0);
        var root_child0_child1 = YGNodeNewWithConfig(config);
        YGNodeStyleSetWidth(root_child0_child1, 80);
        YGNodeStyleSetHeight(root_child0_child1, 80);
        YGNodeInsertChild(root_child0, root_child0_child1, 1);
        YGNodeCalculateLayout(root, float.NaN, float.NaN, YGDirection.LTR);
        Assert.Equal(0f, YGNodeLayoutGetLeft(root));
        Assert.Equal(0f, YGNodeLayoutGetTop(root));
        Assert.Equal(200f, YGNodeLayoutGetWidth(root));
        Assert.Equal(200f, YGNodeLayoutGetHeight(root));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child0));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child0));
        Assert.Equal(200f, YGNodeLayoutGetWidth(root_child0));
        Assert.Equal(160f, YGNodeLayoutGetHeight(root_child0));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child0_child0));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child0_child0));
        Assert.Equal(150f, YGNodeLayoutGetWidth(root_child0_child0));
        Assert.Equal(80f, YGNodeLayoutGetHeight(root_child0_child0));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child0_child1));
        Assert.Equal(80f, YGNodeLayoutGetTop(root_child0_child1));
        Assert.Equal(80f, YGNodeLayoutGetWidth(root_child0_child1));
        Assert.Equal(80f, YGNodeLayoutGetHeight(root_child0_child1));
        YGNodeCalculateLayout(root, float.NaN, float.NaN, YGDirection.RTL);
        Assert.Equal(0f, YGNodeLayoutGetLeft(root));
        Assert.Equal(0f, YGNodeLayoutGetTop(root));
        Assert.Equal(200f, YGNodeLayoutGetWidth(root));
        Assert.Equal(200f, YGNodeLayoutGetHeight(root));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child0));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child0));
        Assert.Equal(200f, YGNodeLayoutGetWidth(root_child0));
        Assert.Equal(160f, YGNodeLayoutGetHeight(root_child0));
        Assert.Equal(50f, YGNodeLayoutGetLeft(root_child0_child0));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child0_child0));
        Assert.Equal(150f, YGNodeLayoutGetWidth(root_child0_child0));
        Assert.Equal(80f, YGNodeLayoutGetHeight(root_child0_child0));
        Assert.Equal(120f, YGNodeLayoutGetLeft(root_child0_child1));
        Assert.Equal(80f, YGNodeLayoutGetTop(root_child0_child1));
        Assert.Equal(80f, YGNodeLayoutGetWidth(root_child0_child1));
        Assert.Equal(80f, YGNodeLayoutGetHeight(root_child0_child1));
        YGNodeFreeRecursive(root);
        YGConfigFree(config);
    }

    [Fact]
    public void wrapped_row_within_align_items_flex_start()
    {
        var config = YGConfigNew();
        var root = YGNodeNewWithConfig(config);
        YGNodeStyleSetPositionType(root, YGPositionType.Absolute);
        YGNodeStyleSetWidth(root, 200);
        YGNodeStyleSetHeight(root, 200);
        YGNodeStyleSetAlignItems(root, YGAlign.FlexStart);
        var root_child0 = YGNodeNewWithConfig(config);
        YGNodeStyleSetFlexDirection(root_child0, YGFlexDirection.Row);
        YGNodeStyleSetFlexWrap(root_child0, YGWrap.Wrap);
        YGNodeInsertChild(root, root_child0, 0);
        var root_child0_child0 = YGNodeNewWithConfig(config);
        YGNodeStyleSetWidth(root_child0_child0, 150);
        YGNodeStyleSetHeight(root_child0_child0, 80);
        YGNodeInsertChild(root_child0, root_child0_child0, 0);
        var root_child0_child1 = YGNodeNewWithConfig(config);
        YGNodeStyleSetWidth(root_child0_child1, 80);
        YGNodeStyleSetHeight(root_child0_child1, 80);
        YGNodeInsertChild(root_child0, root_child0_child1, 1);
        YGNodeCalculateLayout(root, float.NaN, float.NaN, YGDirection.LTR);
        Assert.Equal(0f, YGNodeLayoutGetLeft(root));
        Assert.Equal(0f, YGNodeLayoutGetTop(root));
        Assert.Equal(200f, YGNodeLayoutGetWidth(root));
        Assert.Equal(200f, YGNodeLayoutGetHeight(root));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child0));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child0));
        Assert.Equal(200f, YGNodeLayoutGetWidth(root_child0));
        Assert.Equal(160f, YGNodeLayoutGetHeight(root_child0));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child0_child0));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child0_child0));
        Assert.Equal(150f, YGNodeLayoutGetWidth(root_child0_child0));
        Assert.Equal(80f, YGNodeLayoutGetHeight(root_child0_child0));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child0_child1));
        Assert.Equal(80f, YGNodeLayoutGetTop(root_child0_child1));
        Assert.Equal(80f, YGNodeLayoutGetWidth(root_child0_child1));
        Assert.Equal(80f, YGNodeLayoutGetHeight(root_child0_child1));
        YGNodeCalculateLayout(root, float.NaN, float.NaN, YGDirection.RTL);
        Assert.Equal(0f, YGNodeLayoutGetLeft(root));
        Assert.Equal(0f, YGNodeLayoutGetTop(root));
        Assert.Equal(200f, YGNodeLayoutGetWidth(root));
        Assert.Equal(200f, YGNodeLayoutGetHeight(root));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child0));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child0));
        Assert.Equal(200f, YGNodeLayoutGetWidth(root_child0));
        Assert.Equal(160f, YGNodeLayoutGetHeight(root_child0));
        Assert.Equal(50f, YGNodeLayoutGetLeft(root_child0_child0));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child0_child0));
        Assert.Equal(150f, YGNodeLayoutGetWidth(root_child0_child0));
        Assert.Equal(80f, YGNodeLayoutGetHeight(root_child0_child0));
        Assert.Equal(120f, YGNodeLayoutGetLeft(root_child0_child1));
        Assert.Equal(80f, YGNodeLayoutGetTop(root_child0_child1));
        Assert.Equal(80f, YGNodeLayoutGetWidth(root_child0_child1));
        Assert.Equal(80f, YGNodeLayoutGetHeight(root_child0_child1));
        YGNodeFreeRecursive(root);
        YGConfigFree(config);
    }

    [Fact]
    public void wrapped_row_within_align_items_flex_end()
    {
        var config = YGConfigNew();
        var root = YGNodeNewWithConfig(config);
        YGNodeStyleSetPositionType(root, YGPositionType.Absolute);
        YGNodeStyleSetWidth(root, 200);
        YGNodeStyleSetHeight(root, 200);
        YGNodeStyleSetAlignItems(root, YGAlign.FlexEnd);
        var root_child0 = YGNodeNewWithConfig(config);
        YGNodeStyleSetFlexDirection(root_child0, YGFlexDirection.Row);
        YGNodeStyleSetFlexWrap(root_child0, YGWrap.Wrap);
        YGNodeInsertChild(root, root_child0, 0);
        var root_child0_child0 = YGNodeNewWithConfig(config);
        YGNodeStyleSetWidth(root_child0_child0, 150);
        YGNodeStyleSetHeight(root_child0_child0, 80);
        YGNodeInsertChild(root_child0, root_child0_child0, 0);
        var root_child0_child1 = YGNodeNewWithConfig(config);
        YGNodeStyleSetWidth(root_child0_child1, 80);
        YGNodeStyleSetHeight(root_child0_child1, 80);
        YGNodeInsertChild(root_child0, root_child0_child1, 1);
        YGNodeCalculateLayout(root, float.NaN, float.NaN, YGDirection.LTR);
        Assert.Equal(0f, YGNodeLayoutGetLeft(root));
        Assert.Equal(0f, YGNodeLayoutGetTop(root));
        Assert.Equal(200f, YGNodeLayoutGetWidth(root));
        Assert.Equal(200f, YGNodeLayoutGetHeight(root));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child0));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child0));
        Assert.Equal(200f, YGNodeLayoutGetWidth(root_child0));
        Assert.Equal(160f, YGNodeLayoutGetHeight(root_child0));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child0_child0));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child0_child0));
        Assert.Equal(150f, YGNodeLayoutGetWidth(root_child0_child0));
        Assert.Equal(80f, YGNodeLayoutGetHeight(root_child0_child0));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child0_child1));
        Assert.Equal(80f, YGNodeLayoutGetTop(root_child0_child1));
        Assert.Equal(80f, YGNodeLayoutGetWidth(root_child0_child1));
        Assert.Equal(80f, YGNodeLayoutGetHeight(root_child0_child1));
        YGNodeCalculateLayout(root, float.NaN, float.NaN, YGDirection.RTL);
        Assert.Equal(0f, YGNodeLayoutGetLeft(root));
        Assert.Equal(0f, YGNodeLayoutGetTop(root));
        Assert.Equal(200f, YGNodeLayoutGetWidth(root));
        Assert.Equal(200f, YGNodeLayoutGetHeight(root));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child0));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child0));
        Assert.Equal(200f, YGNodeLayoutGetWidth(root_child0));
        Assert.Equal(160f, YGNodeLayoutGetHeight(root_child0));
        Assert.Equal(50f, YGNodeLayoutGetLeft(root_child0_child0));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child0_child0));
        Assert.Equal(150f, YGNodeLayoutGetWidth(root_child0_child0));
        Assert.Equal(80f, YGNodeLayoutGetHeight(root_child0_child0));
        Assert.Equal(120f, YGNodeLayoutGetLeft(root_child0_child1));
        Assert.Equal(80f, YGNodeLayoutGetTop(root_child0_child1));
        Assert.Equal(80f, YGNodeLayoutGetWidth(root_child0_child1));
        Assert.Equal(80f, YGNodeLayoutGetHeight(root_child0_child1));
        YGNodeFreeRecursive(root);
        YGConfigFree(config);
    }

    [Fact]
    public void wrapped_column_max_height()
    {
        var config = YGConfigNew();
        var root = YGNodeNewWithConfig(config);
        YGNodeStyleSetPositionType(root, YGPositionType.Absolute);
        YGNodeStyleSetHeight(root, 500);
        YGNodeStyleSetWidth(root, 700);
        YGNodeStyleSetAlignItems(root, YGAlign.Center);
        YGNodeStyleSetJustifyContent(root, YGJustify.Center);
        YGNodeStyleSetAlignContent(root, YGAlign.Center);
        YGNodeStyleSetFlexWrap(root, YGWrap.Wrap);
        var root_child0 = YGNodeNewWithConfig(config);
        YGNodeStyleSetWidth(root_child0, 100);
        YGNodeStyleSetHeight(root_child0, 500);
        YGNodeStyleSetMaxHeight(root_child0, 200);
        YGNodeInsertChild(root, root_child0, 0);
        var root_child1 = YGNodeNewWithConfig(config);
        YGNodeStyleSetWidth(root_child1, 200);
        YGNodeStyleSetHeight(root_child1, 200);
        YGNodeStyleSetMargin(root_child1, YGEdge.All, 20);
        YGNodeInsertChild(root, root_child1, 1);
        var root_child2 = YGNodeNewWithConfig(config);
        YGNodeStyleSetWidth(root_child2, 100);
        YGNodeStyleSetHeight(root_child2, 100);
        YGNodeInsertChild(root, root_child2, 2);
        YGNodeCalculateLayout(root, float.NaN, float.NaN, YGDirection.LTR);
        Assert.Equal(0f, YGNodeLayoutGetLeft(root));
        Assert.Equal(0f, YGNodeLayoutGetTop(root));
        Assert.Equal(700f, YGNodeLayoutGetWidth(root));
        Assert.Equal(500f, YGNodeLayoutGetHeight(root));
        Assert.Equal(250f, YGNodeLayoutGetLeft(root_child0));
        Assert.Equal(30f, YGNodeLayoutGetTop(root_child0));
        Assert.Equal(100f, YGNodeLayoutGetWidth(root_child0));
        Assert.Equal(200f, YGNodeLayoutGetHeight(root_child0));
        Assert.Equal(200f, YGNodeLayoutGetLeft(root_child1));
        Assert.Equal(250f, YGNodeLayoutGetTop(root_child1));
        Assert.Equal(200f, YGNodeLayoutGetWidth(root_child1));
        Assert.Equal(200f, YGNodeLayoutGetHeight(root_child1));
        Assert.Equal(420f, YGNodeLayoutGetLeft(root_child2));
        Assert.Equal(200f, YGNodeLayoutGetTop(root_child2));
        Assert.Equal(100f, YGNodeLayoutGetWidth(root_child2));
        Assert.Equal(100f, YGNodeLayoutGetHeight(root_child2));
        YGNodeCalculateLayout(root, float.NaN, float.NaN, YGDirection.RTL);
        Assert.Equal(0f, YGNodeLayoutGetLeft(root));
        Assert.Equal(0f, YGNodeLayoutGetTop(root));
        Assert.Equal(700f, YGNodeLayoutGetWidth(root));
        Assert.Equal(500f, YGNodeLayoutGetHeight(root));
        Assert.Equal(350f, YGNodeLayoutGetLeft(root_child0));
        Assert.Equal(30f, YGNodeLayoutGetTop(root_child0));
        Assert.Equal(100f, YGNodeLayoutGetWidth(root_child0));
        Assert.Equal(200f, YGNodeLayoutGetHeight(root_child0));
        Assert.Equal(300f, YGNodeLayoutGetLeft(root_child1));
        Assert.Equal(250f, YGNodeLayoutGetTop(root_child1));
        Assert.Equal(200f, YGNodeLayoutGetWidth(root_child1));
        Assert.Equal(200f, YGNodeLayoutGetHeight(root_child1));
        Assert.Equal(180f, YGNodeLayoutGetLeft(root_child2));
        Assert.Equal(200f, YGNodeLayoutGetTop(root_child2));
        Assert.Equal(100f, YGNodeLayoutGetWidth(root_child2));
        Assert.Equal(100f, YGNodeLayoutGetHeight(root_child2));
        YGNodeFreeRecursive(root);
        YGConfigFree(config);
    }

    [Fact]
    public void wrapped_column_max_height_flex()
    {
        var config = YGConfigNew();
        var root = YGNodeNewWithConfig(config);
        YGNodeStyleSetPositionType(root, YGPositionType.Absolute);
        YGNodeStyleSetHeight(root, 500);
        YGNodeStyleSetWidth(root, 700);
        YGNodeStyleSetAlignItems(root, YGAlign.Center);
        YGNodeStyleSetJustifyContent(root, YGJustify.Center);
        YGNodeStyleSetAlignContent(root, YGAlign.Center);
        YGNodeStyleSetFlexWrap(root, YGWrap.Wrap);
        var root_child0 = YGNodeNewWithConfig(config);
        YGNodeStyleSetWidth(root_child0, 100);
        YGNodeStyleSetHeight(root_child0, 500);
        YGNodeStyleSetMaxHeight(root_child0, 200);
        YGNodeStyleSetFlexGrow(root_child0, 1);
        YGNodeStyleSetFlexShrink(root_child0, 1);
        YGNodeStyleSetFlexBasisPercent(root_child0, 0);
        YGNodeInsertChild(root, root_child0, 0);
        var root_child1 = YGNodeNewWithConfig(config);
        YGNodeStyleSetWidth(root_child1, 200);
        YGNodeStyleSetHeight(root_child1, 200);
        YGNodeStyleSetMargin(root_child1, YGEdge.All, 20);
        YGNodeStyleSetFlexGrow(root_child1, 1);
        YGNodeStyleSetFlexShrink(root_child1, 1);
        YGNodeStyleSetFlexBasisPercent(root_child1, 0);
        YGNodeInsertChild(root, root_child1, 1);
        var root_child2 = YGNodeNewWithConfig(config);
        YGNodeStyleSetWidth(root_child2, 100);
        YGNodeStyleSetHeight(root_child2, 100);
        YGNodeInsertChild(root, root_child2, 2);
        YGNodeCalculateLayout(root, float.NaN, float.NaN, YGDirection.LTR);
        Assert.Equal(0f, YGNodeLayoutGetLeft(root));
        Assert.Equal(0f, YGNodeLayoutGetTop(root));
        Assert.Equal(700f, YGNodeLayoutGetWidth(root));
        Assert.Equal(500f, YGNodeLayoutGetHeight(root));
        Assert.Equal(300f, YGNodeLayoutGetLeft(root_child0));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child0));
        Assert.Equal(100f, YGNodeLayoutGetWidth(root_child0));
        Assert.Equal(180f, YGNodeLayoutGetHeight(root_child0));
        Assert.Equal(250f, YGNodeLayoutGetLeft(root_child1));
        Assert.Equal(200f, YGNodeLayoutGetTop(root_child1));
        Assert.Equal(200f, YGNodeLayoutGetWidth(root_child1));
        Assert.Equal(180f, YGNodeLayoutGetHeight(root_child1));
        Assert.Equal(300f, YGNodeLayoutGetLeft(root_child2));
        Assert.Equal(400f, YGNodeLayoutGetTop(root_child2));
        Assert.Equal(100f, YGNodeLayoutGetWidth(root_child2));
        Assert.Equal(100f, YGNodeLayoutGetHeight(root_child2));
        YGNodeCalculateLayout(root, float.NaN, float.NaN, YGDirection.RTL);
        Assert.Equal(0f, YGNodeLayoutGetLeft(root));
        Assert.Equal(0f, YGNodeLayoutGetTop(root));
        Assert.Equal(700f, YGNodeLayoutGetWidth(root));
        Assert.Equal(500f, YGNodeLayoutGetHeight(root));
        Assert.Equal(300f, YGNodeLayoutGetLeft(root_child0));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child0));
        Assert.Equal(100f, YGNodeLayoutGetWidth(root_child0));
        Assert.Equal(180f, YGNodeLayoutGetHeight(root_child0));
        Assert.Equal(250f, YGNodeLayoutGetLeft(root_child1));
        Assert.Equal(200f, YGNodeLayoutGetTop(root_child1));
        Assert.Equal(200f, YGNodeLayoutGetWidth(root_child1));
        Assert.Equal(180f, YGNodeLayoutGetHeight(root_child1));
        Assert.Equal(300f, YGNodeLayoutGetLeft(root_child2));
        Assert.Equal(400f, YGNodeLayoutGetTop(root_child2));
        Assert.Equal(100f, YGNodeLayoutGetWidth(root_child2));
        Assert.Equal(100f, YGNodeLayoutGetHeight(root_child2));
        YGNodeFreeRecursive(root);
        YGConfigFree(config);
    }

    [Fact]
    public void wrap_nodes_with_content_sizing_overflowing_margin()
    {
        var config = YGConfigNew();
        var root = YGNodeNewWithConfig(config);
        YGNodeStyleSetPositionType(root, YGPositionType.Absolute);
        YGNodeStyleSetWidth(root, 500);
        YGNodeStyleSetHeight(root, 500);
        var root_child0 = YGNodeNewWithConfig(config);
        YGNodeStyleSetFlexDirection(root_child0, YGFlexDirection.Row);
        YGNodeStyleSetFlexWrap(root_child0, YGWrap.Wrap);
        YGNodeStyleSetWidth(root_child0, 85);
        YGNodeInsertChild(root, root_child0, 0);
        var root_child0_child0 = YGNodeNewWithConfig(config);
        YGNodeInsertChild(root_child0, root_child0_child0, 0);
        var root_child0_child0_child0 = YGNodeNewWithConfig(config);
        YGNodeStyleSetHeight(root_child0_child0_child0, 40);
        YGNodeStyleSetWidth(root_child0_child0_child0, 40);
        YGNodeInsertChild(root_child0_child0, root_child0_child0_child0, 0);
        var root_child0_child1 = YGNodeNewWithConfig(config);
        YGNodeStyleSetMargin(root_child0_child1, YGEdge.Right, 10);
        YGNodeInsertChild(root_child0, root_child0_child1, 1);
        var root_child0_child1_child0 = YGNodeNewWithConfig(config);
        YGNodeStyleSetHeight(root_child0_child1_child0, 40);
        YGNodeStyleSetWidth(root_child0_child1_child0, 40);
        YGNodeInsertChild(root_child0_child1, root_child0_child1_child0, 0);
        YGNodeCalculateLayout(root, float.NaN, float.NaN, YGDirection.LTR);
        Assert.Equal(0f, YGNodeLayoutGetLeft(root));
        Assert.Equal(0f, YGNodeLayoutGetTop(root));
        Assert.Equal(500f, YGNodeLayoutGetWidth(root));
        Assert.Equal(500f, YGNodeLayoutGetHeight(root));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child0));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child0));
        Assert.Equal(85f, YGNodeLayoutGetWidth(root_child0));
        Assert.Equal(80f, YGNodeLayoutGetHeight(root_child0));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child0_child0));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child0_child0));
        Assert.Equal(40f, YGNodeLayoutGetWidth(root_child0_child0));
        Assert.Equal(40f, YGNodeLayoutGetHeight(root_child0_child0));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child0_child0_child0));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child0_child0_child0));
        Assert.Equal(40f, YGNodeLayoutGetWidth(root_child0_child0_child0));
        Assert.Equal(40f, YGNodeLayoutGetHeight(root_child0_child0_child0));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child0_child1));
        Assert.Equal(40f, YGNodeLayoutGetTop(root_child0_child1));
        Assert.Equal(40f, YGNodeLayoutGetWidth(root_child0_child1));
        Assert.Equal(40f, YGNodeLayoutGetHeight(root_child0_child1));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child0_child1_child0));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child0_child1_child0));
        Assert.Equal(40f, YGNodeLayoutGetWidth(root_child0_child1_child0));
        Assert.Equal(40f, YGNodeLayoutGetHeight(root_child0_child1_child0));
        YGNodeCalculateLayout(root, float.NaN, float.NaN, YGDirection.RTL);
        Assert.Equal(0f, YGNodeLayoutGetLeft(root));
        Assert.Equal(0f, YGNodeLayoutGetTop(root));
        Assert.Equal(500f, YGNodeLayoutGetWidth(root));
        Assert.Equal(500f, YGNodeLayoutGetHeight(root));
        Assert.Equal(415f, YGNodeLayoutGetLeft(root_child0));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child0));
        Assert.Equal(85f, YGNodeLayoutGetWidth(root_child0));
        Assert.Equal(80f, YGNodeLayoutGetHeight(root_child0));
        Assert.Equal(45f, YGNodeLayoutGetLeft(root_child0_child0));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child0_child0));
        Assert.Equal(40f, YGNodeLayoutGetWidth(root_child0_child0));
        Assert.Equal(40f, YGNodeLayoutGetHeight(root_child0_child0));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child0_child0_child0));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child0_child0_child0));
        Assert.Equal(40f, YGNodeLayoutGetWidth(root_child0_child0_child0));
        Assert.Equal(40f, YGNodeLayoutGetHeight(root_child0_child0_child0));
        Assert.Equal(35f, YGNodeLayoutGetLeft(root_child0_child1));
        Assert.Equal(40f, YGNodeLayoutGetTop(root_child0_child1));
        Assert.Equal(40f, YGNodeLayoutGetWidth(root_child0_child1));
        Assert.Equal(40f, YGNodeLayoutGetHeight(root_child0_child1));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child0_child1_child0));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child0_child1_child0));
        Assert.Equal(40f, YGNodeLayoutGetWidth(root_child0_child1_child0));
        Assert.Equal(40f, YGNodeLayoutGetHeight(root_child0_child1_child0));
        YGNodeFreeRecursive(root);
        YGConfigFree(config);
    }

    [Fact]
    public void wrap_nodes_with_content_sizing_margin_cross()
    {
        var config = YGConfigNew();
        var root = YGNodeNewWithConfig(config);
        YGNodeStyleSetPositionType(root, YGPositionType.Absolute);
        YGNodeStyleSetWidth(root, 500);
        YGNodeStyleSetHeight(root, 500);
        var root_child0 = YGNodeNewWithConfig(config);
        YGNodeStyleSetFlexDirection(root_child0, YGFlexDirection.Row);
        YGNodeStyleSetFlexWrap(root_child0, YGWrap.Wrap);
        YGNodeStyleSetWidth(root_child0, 70);
        YGNodeInsertChild(root, root_child0, 0);
        var root_child0_child0 = YGNodeNewWithConfig(config);
        YGNodeInsertChild(root_child0, root_child0_child0, 0);
        var root_child0_child0_child0 = YGNodeNewWithConfig(config);
        YGNodeStyleSetHeight(root_child0_child0_child0, 40);
        YGNodeStyleSetWidth(root_child0_child0_child0, 40);
        YGNodeInsertChild(root_child0_child0, root_child0_child0_child0, 0);
        var root_child0_child1 = YGNodeNewWithConfig(config);
        YGNodeStyleSetMargin(root_child0_child1, YGEdge.Top, 10);
        YGNodeInsertChild(root_child0, root_child0_child1, 1);
        var root_child0_child1_child0 = YGNodeNewWithConfig(config);
        YGNodeStyleSetHeight(root_child0_child1_child0, 40);
        YGNodeStyleSetWidth(root_child0_child1_child0, 40);
        YGNodeInsertChild(root_child0_child1, root_child0_child1_child0, 0);
        YGNodeCalculateLayout(root, float.NaN, float.NaN, YGDirection.LTR);
        Assert.Equal(0f, YGNodeLayoutGetLeft(root));
        Assert.Equal(0f, YGNodeLayoutGetTop(root));
        Assert.Equal(500f, YGNodeLayoutGetWidth(root));
        Assert.Equal(500f, YGNodeLayoutGetHeight(root));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child0));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child0));
        Assert.Equal(70f, YGNodeLayoutGetWidth(root_child0));
        Assert.Equal(90f, YGNodeLayoutGetHeight(root_child0));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child0_child0));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child0_child0));
        Assert.Equal(40f, YGNodeLayoutGetWidth(root_child0_child0));
        Assert.Equal(40f, YGNodeLayoutGetHeight(root_child0_child0));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child0_child0_child0));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child0_child0_child0));
        Assert.Equal(40f, YGNodeLayoutGetWidth(root_child0_child0_child0));
        Assert.Equal(40f, YGNodeLayoutGetHeight(root_child0_child0_child0));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child0_child1));
        Assert.Equal(50f, YGNodeLayoutGetTop(root_child0_child1));
        Assert.Equal(40f, YGNodeLayoutGetWidth(root_child0_child1));
        Assert.Equal(40f, YGNodeLayoutGetHeight(root_child0_child1));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child0_child1_child0));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child0_child1_child0));
        Assert.Equal(40f, YGNodeLayoutGetWidth(root_child0_child1_child0));
        Assert.Equal(40f, YGNodeLayoutGetHeight(root_child0_child1_child0));
        YGNodeCalculateLayout(root, float.NaN, float.NaN, YGDirection.RTL);
        Assert.Equal(0f, YGNodeLayoutGetLeft(root));
        Assert.Equal(0f, YGNodeLayoutGetTop(root));
        Assert.Equal(500f, YGNodeLayoutGetWidth(root));
        Assert.Equal(500f, YGNodeLayoutGetHeight(root));
        Assert.Equal(430f, YGNodeLayoutGetLeft(root_child0));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child0));
        Assert.Equal(70f, YGNodeLayoutGetWidth(root_child0));
        Assert.Equal(90f, YGNodeLayoutGetHeight(root_child0));
        Assert.Equal(30f, YGNodeLayoutGetLeft(root_child0_child0));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child0_child0));
        Assert.Equal(40f, YGNodeLayoutGetWidth(root_child0_child0));
        Assert.Equal(40f, YGNodeLayoutGetHeight(root_child0_child0));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child0_child0_child0));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child0_child0_child0));
        Assert.Equal(40f, YGNodeLayoutGetWidth(root_child0_child0_child0));
        Assert.Equal(40f, YGNodeLayoutGetHeight(root_child0_child0_child0));
        Assert.Equal(30f, YGNodeLayoutGetLeft(root_child0_child1));
        Assert.Equal(50f, YGNodeLayoutGetTop(root_child0_child1));
        Assert.Equal(40f, YGNodeLayoutGetWidth(root_child0_child1));
        Assert.Equal(40f, YGNodeLayoutGetHeight(root_child0_child1));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child0_child1_child0));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child0_child1_child0));
        Assert.Equal(40f, YGNodeLayoutGetWidth(root_child0_child1_child0));
        Assert.Equal(40f, YGNodeLayoutGetHeight(root_child0_child1_child0));
        YGNodeFreeRecursive(root);
        YGConfigFree(config);
    }

    [Fact]
    public void wrap_with_min_cross_axis()
    {
        var config = YGConfigNew();
        var root = YGNodeNewWithConfig(config);
        YGNodeStyleSetPositionType(root, YGPositionType.Absolute);
        YGNodeStyleSetWidth(root, 500);
        YGNodeStyleSetMinHeight(root, 500);
        YGNodeStyleSetFlexDirection(root, YGFlexDirection.Row);
        YGNodeStyleSetFlexWrap(root, YGWrap.Wrap);
        var root_child0 = YGNodeNewWithConfig(config);
        YGNodeStyleSetWidth(root_child0, 400);
        YGNodeStyleSetHeight(root_child0, 200);
        YGNodeInsertChild(root, root_child0, 0);
        var root_child1 = YGNodeNewWithConfig(config);
        YGNodeStyleSetWidth(root_child1, 400);
        YGNodeStyleSetHeight(root_child1, 200);
        YGNodeInsertChild(root, root_child1, 1);
        YGNodeCalculateLayout(root, float.NaN, float.NaN, YGDirection.LTR);
        Assert.Equal(0f, YGNodeLayoutGetLeft(root));
        Assert.Equal(0f, YGNodeLayoutGetTop(root));
        Assert.Equal(500f, YGNodeLayoutGetWidth(root));
        Assert.Equal(500f, YGNodeLayoutGetHeight(root));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child0));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child0));
        Assert.Equal(400f, YGNodeLayoutGetWidth(root_child0));
        Assert.Equal(200f, YGNodeLayoutGetHeight(root_child0));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child1));
        Assert.Equal(200f, YGNodeLayoutGetTop(root_child1));
        Assert.Equal(400f, YGNodeLayoutGetWidth(root_child1));
        Assert.Equal(200f, YGNodeLayoutGetHeight(root_child1));
        YGNodeCalculateLayout(root, float.NaN, float.NaN, YGDirection.RTL);
        Assert.Equal(0f, YGNodeLayoutGetLeft(root));
        Assert.Equal(0f, YGNodeLayoutGetTop(root));
        Assert.Equal(500f, YGNodeLayoutGetWidth(root));
        Assert.Equal(500f, YGNodeLayoutGetHeight(root));
        Assert.Equal(100f, YGNodeLayoutGetLeft(root_child0));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child0));
        Assert.Equal(400f, YGNodeLayoutGetWidth(root_child0));
        Assert.Equal(200f, YGNodeLayoutGetHeight(root_child0));
        Assert.Equal(100f, YGNodeLayoutGetLeft(root_child1));
        Assert.Equal(200f, YGNodeLayoutGetTop(root_child1));
        Assert.Equal(400f, YGNodeLayoutGetWidth(root_child1));
        Assert.Equal(200f, YGNodeLayoutGetHeight(root_child1));
        YGNodeFreeRecursive(root);
        YGConfigFree(config);
    }

    [Fact]
    public void wrap_with_max_cross_axis()
    {
        var config = YGConfigNew();
        var root = YGNodeNewWithConfig(config);
        YGNodeStyleSetPositionType(root, YGPositionType.Absolute);
        YGNodeStyleSetWidth(root, 500);
        YGNodeStyleSetMaxHeight(root, 500);
        YGNodeStyleSetFlexDirection(root, YGFlexDirection.Row);
        YGNodeStyleSetFlexWrap(root, YGWrap.Wrap);
        var root_child0 = YGNodeNewWithConfig(config);
        YGNodeStyleSetWidth(root_child0, 400);
        YGNodeStyleSetHeight(root_child0, 200);
        YGNodeInsertChild(root, root_child0, 0);
        var root_child1 = YGNodeNewWithConfig(config);
        YGNodeStyleSetWidth(root_child1, 400);
        YGNodeStyleSetHeight(root_child1, 200);
        YGNodeInsertChild(root, root_child1, 1);
        YGNodeCalculateLayout(root, float.NaN, float.NaN, YGDirection.LTR);
        Assert.Equal(0f, YGNodeLayoutGetLeft(root));
        Assert.Equal(0f, YGNodeLayoutGetTop(root));
        Assert.Equal(500f, YGNodeLayoutGetWidth(root));
        Assert.Equal(400f, YGNodeLayoutGetHeight(root));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child0));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child0));
        Assert.Equal(400f, YGNodeLayoutGetWidth(root_child0));
        Assert.Equal(200f, YGNodeLayoutGetHeight(root_child0));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child1));
        Assert.Equal(200f, YGNodeLayoutGetTop(root_child1));
        Assert.Equal(400f, YGNodeLayoutGetWidth(root_child1));
        Assert.Equal(200f, YGNodeLayoutGetHeight(root_child1));
        YGNodeCalculateLayout(root, float.NaN, float.NaN, YGDirection.RTL);
        Assert.Equal(0f, YGNodeLayoutGetLeft(root));
        Assert.Equal(0f, YGNodeLayoutGetTop(root));
        Assert.Equal(500f, YGNodeLayoutGetWidth(root));
        Assert.Equal(400f, YGNodeLayoutGetHeight(root));
        Assert.Equal(100f, YGNodeLayoutGetLeft(root_child0));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child0));
        Assert.Equal(400f, YGNodeLayoutGetWidth(root_child0));
        Assert.Equal(200f, YGNodeLayoutGetHeight(root_child0));
        Assert.Equal(100f, YGNodeLayoutGetLeft(root_child1));
        Assert.Equal(200f, YGNodeLayoutGetTop(root_child1));
        Assert.Equal(400f, YGNodeLayoutGetWidth(root_child1));
        Assert.Equal(200f, YGNodeLayoutGetHeight(root_child1));
        YGNodeFreeRecursive(root);
        YGConfigFree(config);
    }

    [Fact]
    public void nowrap_expands_flexline_box_to_min_cross()
    {
        var config = YGConfigNew();
        var root = YGNodeNewWithConfig(config);
        YGNodeStyleSetPositionType(root, YGPositionType.Absolute);
        YGNodeStyleSetMinHeight(root, 400);
        YGNodeStyleSetFlexDirection(root, YGFlexDirection.Row);
        var root_child0 = YGNodeNewWithConfig(config);
        YGNodeStyleSetFlexGrow(root_child0, 1);
        YGNodeStyleSetFlexShrink(root_child0, 1);
        YGNodeStyleSetFlexBasisPercent(root_child0, 0);
        YGNodeInsertChild(root, root_child0, 0);
        YGNodeCalculateLayout(root, float.NaN, float.NaN, YGDirection.LTR);
        Assert.Equal(0f, YGNodeLayoutGetLeft(root));
        Assert.Equal(0f, YGNodeLayoutGetTop(root));
        Assert.Equal(0f, YGNodeLayoutGetWidth(root));
        Assert.Equal(400f, YGNodeLayoutGetHeight(root));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child0));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child0));
        Assert.Equal(0f, YGNodeLayoutGetWidth(root_child0));
        Assert.Equal(400f, YGNodeLayoutGetHeight(root_child0));
        YGNodeCalculateLayout(root, float.NaN, float.NaN, YGDirection.RTL);
        Assert.Equal(0f, YGNodeLayoutGetLeft(root));
        Assert.Equal(0f, YGNodeLayoutGetTop(root));
        Assert.Equal(0f, YGNodeLayoutGetWidth(root));
        Assert.Equal(400f, YGNodeLayoutGetHeight(root));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child0));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child0));
        Assert.Equal(0f, YGNodeLayoutGetWidth(root_child0));
        Assert.Equal(400f, YGNodeLayoutGetHeight(root_child0));
        YGNodeFreeRecursive(root);
        YGConfigFree(config);
    }

    [Fact]
    public void wrap_does_not_impose_min_cross_onto_single_flexline()
    {
        var config = YGConfigNew();
        var root = YGNodeNewWithConfig(config);
        YGNodeStyleSetPositionType(root, YGPositionType.Absolute);
        YGNodeStyleSetMinHeight(root, 400);
        YGNodeStyleSetFlexDirection(root, YGFlexDirection.Row);
        YGNodeStyleSetFlexWrap(root, YGWrap.Wrap);
        var root_child0 = YGNodeNewWithConfig(config);
        YGNodeStyleSetFlexGrow(root_child0, 1);
        YGNodeStyleSetFlexShrink(root_child0, 1);
        YGNodeStyleSetFlexBasisPercent(root_child0, 0);
        YGNodeInsertChild(root, root_child0, 0);
        YGNodeCalculateLayout(root, float.NaN, float.NaN, YGDirection.LTR);
        Assert.Equal(0f, YGNodeLayoutGetLeft(root));
        Assert.Equal(0f, YGNodeLayoutGetTop(root));
        Assert.Equal(0f, YGNodeLayoutGetWidth(root));
        Assert.Equal(400f, YGNodeLayoutGetHeight(root));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child0));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child0));
        Assert.Equal(0f, YGNodeLayoutGetWidth(root_child0));
        Assert.Equal(0f, YGNodeLayoutGetHeight(root_child0));
        YGNodeCalculateLayout(root, float.NaN, float.NaN, YGDirection.RTL);
        Assert.Equal(0f, YGNodeLayoutGetLeft(root));
        Assert.Equal(0f, YGNodeLayoutGetTop(root));
        Assert.Equal(0f, YGNodeLayoutGetWidth(root));
        Assert.Equal(400f, YGNodeLayoutGetHeight(root));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child0));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child0));
        Assert.Equal(0f, YGNodeLayoutGetWidth(root_child0));
        Assert.Equal(0f, YGNodeLayoutGetHeight(root_child0));
        YGNodeFreeRecursive(root);
        YGConfigFree(config);
    }

}

