// Copyright (c) Meta Platforms, Inc. and affiliates.
// This source code is licensed under the MIT license found in the
// LICENSE file in the root directory of this source tree.
// @generated from yoga/tests/generated/YGRoundingTest.cpp

using Xunit;
using Facebook.Yoga;
using static Facebook.Yoga.YGNodeAPI;
using static Facebook.Yoga.YGNodeStyleAPI;
using static Facebook.Yoga.YGNodeLayoutAPI;
using static Facebook.Yoga.YGConfigAPI;

namespace Yoga.Tests;

public class YGRoundingTest
{
    [Fact]
    public void rounding_flex_basis_flex_grow_row_width_of_100()
    {
        var config = YGConfigNew();
        var root = YGNodeNewWithConfig(config);
        YGNodeStyleSetPositionType(root, YGPositionType.Absolute);
        YGNodeStyleSetWidth(root, 100);
        YGNodeStyleSetHeight(root, 100);
        YGNodeStyleSetFlexDirection(root, YGFlexDirection.Row);
        var root_child0 = YGNodeNewWithConfig(config);
        YGNodeStyleSetFlexGrow(root_child0, 1);
        YGNodeInsertChild(root, root_child0, 0);
        var root_child1 = YGNodeNewWithConfig(config);
        YGNodeStyleSetFlexGrow(root_child1, 1);
        YGNodeInsertChild(root, root_child1, 1);
        var root_child2 = YGNodeNewWithConfig(config);
        YGNodeStyleSetFlexGrow(root_child2, 1);
        YGNodeInsertChild(root, root_child2, 2);
        YGNodeCalculateLayout(root, float.NaN, float.NaN, YGDirection.LTR);
        Assert.Equal(0f, YGNodeLayoutGetLeft(root));
        Assert.Equal(0f, YGNodeLayoutGetTop(root));
        Assert.Equal(100f, YGNodeLayoutGetWidth(root));
        Assert.Equal(100f, YGNodeLayoutGetHeight(root));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child0));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child0));
        Assert.Equal(33f, YGNodeLayoutGetWidth(root_child0));
        Assert.Equal(100f, YGNodeLayoutGetHeight(root_child0));
        Assert.Equal(33f, YGNodeLayoutGetLeft(root_child1));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child1));
        Assert.Equal(34f, YGNodeLayoutGetWidth(root_child1));
        Assert.Equal(100f, YGNodeLayoutGetHeight(root_child1));
        Assert.Equal(67f, YGNodeLayoutGetLeft(root_child2));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child2));
        Assert.Equal(33f, YGNodeLayoutGetWidth(root_child2));
        Assert.Equal(100f, YGNodeLayoutGetHeight(root_child2));
        YGNodeCalculateLayout(root, float.NaN, float.NaN, YGDirection.RTL);
        Assert.Equal(0f, YGNodeLayoutGetLeft(root));
        Assert.Equal(0f, YGNodeLayoutGetTop(root));
        Assert.Equal(100f, YGNodeLayoutGetWidth(root));
        Assert.Equal(100f, YGNodeLayoutGetHeight(root));
        Assert.Equal(67f, YGNodeLayoutGetLeft(root_child0));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child0));
        Assert.Equal(33f, YGNodeLayoutGetWidth(root_child0));
        Assert.Equal(100f, YGNodeLayoutGetHeight(root_child0));
        Assert.Equal(33f, YGNodeLayoutGetLeft(root_child1));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child1));
        Assert.Equal(34f, YGNodeLayoutGetWidth(root_child1));
        Assert.Equal(100f, YGNodeLayoutGetHeight(root_child1));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child2));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child2));
        Assert.Equal(33f, YGNodeLayoutGetWidth(root_child2));
        Assert.Equal(100f, YGNodeLayoutGetHeight(root_child2));
        YGNodeFreeRecursive(root);
        YGConfigFree(config);
    }

    [Fact]
    public void rounding_flex_basis_flex_grow_row_prime_number_width()
    {
        var config = YGConfigNew();
        var root = YGNodeNewWithConfig(config);
        YGNodeStyleSetPositionType(root, YGPositionType.Absolute);
        YGNodeStyleSetWidth(root, 113);
        YGNodeStyleSetHeight(root, 100);
        YGNodeStyleSetFlexDirection(root, YGFlexDirection.Row);
        var root_child0 = YGNodeNewWithConfig(config);
        YGNodeStyleSetFlexGrow(root_child0, 1);
        YGNodeInsertChild(root, root_child0, 0);
        var root_child1 = YGNodeNewWithConfig(config);
        YGNodeStyleSetFlexGrow(root_child1, 1);
        YGNodeInsertChild(root, root_child1, 1);
        var root_child2 = YGNodeNewWithConfig(config);
        YGNodeStyleSetFlexGrow(root_child2, 1);
        YGNodeInsertChild(root, root_child2, 2);
        var root_child3 = YGNodeNewWithConfig(config);
        YGNodeStyleSetFlexGrow(root_child3, 1);
        YGNodeInsertChild(root, root_child3, 3);
        var root_child4 = YGNodeNewWithConfig(config);
        YGNodeStyleSetFlexGrow(root_child4, 1);
        YGNodeInsertChild(root, root_child4, 4);
        YGNodeCalculateLayout(root, float.NaN, float.NaN, YGDirection.LTR);
        Assert.Equal(0f, YGNodeLayoutGetLeft(root));
        Assert.Equal(0f, YGNodeLayoutGetTop(root));
        Assert.Equal(113f, YGNodeLayoutGetWidth(root));
        Assert.Equal(100f, YGNodeLayoutGetHeight(root));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child0));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child0));
        Assert.Equal(23f, YGNodeLayoutGetWidth(root_child0));
        Assert.Equal(100f, YGNodeLayoutGetHeight(root_child0));
        Assert.Equal(23f, YGNodeLayoutGetLeft(root_child1));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child1));
        Assert.Equal(22f, YGNodeLayoutGetWidth(root_child1));
        Assert.Equal(100f, YGNodeLayoutGetHeight(root_child1));
        Assert.Equal(45f, YGNodeLayoutGetLeft(root_child2));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child2));
        Assert.Equal(23f, YGNodeLayoutGetWidth(root_child2));
        Assert.Equal(100f, YGNodeLayoutGetHeight(root_child2));
        Assert.Equal(68f, YGNodeLayoutGetLeft(root_child3));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child3));
        Assert.Equal(22f, YGNodeLayoutGetWidth(root_child3));
        Assert.Equal(100f, YGNodeLayoutGetHeight(root_child3));
        Assert.Equal(90f, YGNodeLayoutGetLeft(root_child4));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child4));
        Assert.Equal(23f, YGNodeLayoutGetWidth(root_child4));
        Assert.Equal(100f, YGNodeLayoutGetHeight(root_child4));
        YGNodeCalculateLayout(root, float.NaN, float.NaN, YGDirection.RTL);
        Assert.Equal(0f, YGNodeLayoutGetLeft(root));
        Assert.Equal(0f, YGNodeLayoutGetTop(root));
        Assert.Equal(113f, YGNodeLayoutGetWidth(root));
        Assert.Equal(100f, YGNodeLayoutGetHeight(root));
        Assert.Equal(90f, YGNodeLayoutGetLeft(root_child0));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child0));
        Assert.Equal(23f, YGNodeLayoutGetWidth(root_child0));
        Assert.Equal(100f, YGNodeLayoutGetHeight(root_child0));
        Assert.Equal(68f, YGNodeLayoutGetLeft(root_child1));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child1));
        Assert.Equal(22f, YGNodeLayoutGetWidth(root_child1));
        Assert.Equal(100f, YGNodeLayoutGetHeight(root_child1));
        Assert.Equal(45f, YGNodeLayoutGetLeft(root_child2));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child2));
        Assert.Equal(23f, YGNodeLayoutGetWidth(root_child2));
        Assert.Equal(100f, YGNodeLayoutGetHeight(root_child2));
        Assert.Equal(23f, YGNodeLayoutGetLeft(root_child3));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child3));
        Assert.Equal(22f, YGNodeLayoutGetWidth(root_child3));
        Assert.Equal(100f, YGNodeLayoutGetHeight(root_child3));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child4));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child4));
        Assert.Equal(23f, YGNodeLayoutGetWidth(root_child4));
        Assert.Equal(100f, YGNodeLayoutGetHeight(root_child4));
        YGNodeFreeRecursive(root);
        YGConfigFree(config);
    }

    [Fact]
    public void rounding_flex_basis_flex_shrink_row()
    {
        var config = YGConfigNew();
        var root = YGNodeNewWithConfig(config);
        YGNodeStyleSetPositionType(root, YGPositionType.Absolute);
        YGNodeStyleSetWidth(root, 101);
        YGNodeStyleSetHeight(root, 100);
        YGNodeStyleSetFlexDirection(root, YGFlexDirection.Row);
        var root_child0 = YGNodeNewWithConfig(config);
        YGNodeStyleSetFlexBasis(root_child0, 100);
        YGNodeStyleSetFlexShrink(root_child0, 1);
        YGNodeInsertChild(root, root_child0, 0);
        var root_child1 = YGNodeNewWithConfig(config);
        YGNodeStyleSetFlexBasis(root_child1, 25);
        YGNodeInsertChild(root, root_child1, 1);
        var root_child2 = YGNodeNewWithConfig(config);
        YGNodeStyleSetFlexBasis(root_child2, 25);
        YGNodeInsertChild(root, root_child2, 2);
        YGNodeCalculateLayout(root, float.NaN, float.NaN, YGDirection.LTR);
        Assert.Equal(0f, YGNodeLayoutGetLeft(root));
        Assert.Equal(0f, YGNodeLayoutGetTop(root));
        Assert.Equal(101f, YGNodeLayoutGetWidth(root));
        Assert.Equal(100f, YGNodeLayoutGetHeight(root));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child0));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child0));
        Assert.Equal(51f, YGNodeLayoutGetWidth(root_child0));
        Assert.Equal(100f, YGNodeLayoutGetHeight(root_child0));
        Assert.Equal(51f, YGNodeLayoutGetLeft(root_child1));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child1));
        Assert.Equal(25f, YGNodeLayoutGetWidth(root_child1));
        Assert.Equal(100f, YGNodeLayoutGetHeight(root_child1));
        Assert.Equal(76f, YGNodeLayoutGetLeft(root_child2));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child2));
        Assert.Equal(25f, YGNodeLayoutGetWidth(root_child2));
        Assert.Equal(100f, YGNodeLayoutGetHeight(root_child2));
        YGNodeCalculateLayout(root, float.NaN, float.NaN, YGDirection.RTL);
        Assert.Equal(0f, YGNodeLayoutGetLeft(root));
        Assert.Equal(0f, YGNodeLayoutGetTop(root));
        Assert.Equal(101f, YGNodeLayoutGetWidth(root));
        Assert.Equal(100f, YGNodeLayoutGetHeight(root));
        Assert.Equal(50f, YGNodeLayoutGetLeft(root_child0));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child0));
        Assert.Equal(51f, YGNodeLayoutGetWidth(root_child0));
        Assert.Equal(100f, YGNodeLayoutGetHeight(root_child0));
        Assert.Equal(25f, YGNodeLayoutGetLeft(root_child1));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child1));
        Assert.Equal(25f, YGNodeLayoutGetWidth(root_child1));
        Assert.Equal(100f, YGNodeLayoutGetHeight(root_child1));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child2));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child2));
        Assert.Equal(25f, YGNodeLayoutGetWidth(root_child2));
        Assert.Equal(100f, YGNodeLayoutGetHeight(root_child2));
        YGNodeFreeRecursive(root);
        YGConfigFree(config);
    }

    [Fact]
    public void rounding_flex_basis_overrides_main_size()
    {
        var config = YGConfigNew();
        var root = YGNodeNewWithConfig(config);
        YGNodeStyleSetPositionType(root, YGPositionType.Absolute);
        YGNodeStyleSetHeight(root, 113);
        YGNodeStyleSetWidth(root, 100);
        var root_child0 = YGNodeNewWithConfig(config);
        YGNodeStyleSetHeight(root_child0, 20);
        YGNodeStyleSetFlexGrow(root_child0, 1);
        YGNodeStyleSetFlexBasis(root_child0, 50);
        YGNodeInsertChild(root, root_child0, 0);
        var root_child1 = YGNodeNewWithConfig(config);
        YGNodeStyleSetHeight(root_child1, 10);
        YGNodeStyleSetFlexGrow(root_child1, 1);
        YGNodeInsertChild(root, root_child1, 1);
        var root_child2 = YGNodeNewWithConfig(config);
        YGNodeStyleSetHeight(root_child2, 10);
        YGNodeStyleSetFlexGrow(root_child2, 1);
        YGNodeInsertChild(root, root_child2, 2);
        YGNodeCalculateLayout(root, float.NaN, float.NaN, YGDirection.LTR);
        Assert.Equal(0f, YGNodeLayoutGetLeft(root));
        Assert.Equal(0f, YGNodeLayoutGetTop(root));
        Assert.Equal(100f, YGNodeLayoutGetWidth(root));
        Assert.Equal(113f, YGNodeLayoutGetHeight(root));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child0));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child0));
        Assert.Equal(100f, YGNodeLayoutGetWidth(root_child0));
        Assert.Equal(64f, YGNodeLayoutGetHeight(root_child0));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child1));
        Assert.Equal(64f, YGNodeLayoutGetTop(root_child1));
        Assert.Equal(100f, YGNodeLayoutGetWidth(root_child1));
        Assert.Equal(25f, YGNodeLayoutGetHeight(root_child1));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child2));
        Assert.Equal(89f, YGNodeLayoutGetTop(root_child2));
        Assert.Equal(100f, YGNodeLayoutGetWidth(root_child2));
        Assert.Equal(24f, YGNodeLayoutGetHeight(root_child2));
        YGNodeCalculateLayout(root, float.NaN, float.NaN, YGDirection.RTL);
        Assert.Equal(0f, YGNodeLayoutGetLeft(root));
        Assert.Equal(0f, YGNodeLayoutGetTop(root));
        Assert.Equal(100f, YGNodeLayoutGetWidth(root));
        Assert.Equal(113f, YGNodeLayoutGetHeight(root));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child0));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child0));
        Assert.Equal(100f, YGNodeLayoutGetWidth(root_child0));
        Assert.Equal(64f, YGNodeLayoutGetHeight(root_child0));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child1));
        Assert.Equal(64f, YGNodeLayoutGetTop(root_child1));
        Assert.Equal(100f, YGNodeLayoutGetWidth(root_child1));
        Assert.Equal(25f, YGNodeLayoutGetHeight(root_child1));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child2));
        Assert.Equal(89f, YGNodeLayoutGetTop(root_child2));
        Assert.Equal(100f, YGNodeLayoutGetWidth(root_child2));
        Assert.Equal(24f, YGNodeLayoutGetHeight(root_child2));
        YGNodeFreeRecursive(root);
        YGConfigFree(config);
    }

    [Fact]
    public void rounding_total_fractial()
    {
        var config = YGConfigNew();
        var root = YGNodeNewWithConfig(config);
        YGNodeStyleSetPositionType(root, YGPositionType.Absolute);
        YGNodeStyleSetHeight(root, 113.4f);
        YGNodeStyleSetWidth(root, 87.4f);
        var root_child0 = YGNodeNewWithConfig(config);
        YGNodeStyleSetHeight(root_child0, 20.3f);
        YGNodeStyleSetFlexGrow(root_child0, 0.7f);
        YGNodeStyleSetFlexBasis(root_child0, 50.3f);
        YGNodeInsertChild(root, root_child0, 0);
        var root_child1 = YGNodeNewWithConfig(config);
        YGNodeStyleSetHeight(root_child1, 10);
        YGNodeStyleSetFlexGrow(root_child1, 1.6f);
        YGNodeInsertChild(root, root_child1, 1);
        var root_child2 = YGNodeNewWithConfig(config);
        YGNodeStyleSetHeight(root_child2, 10.7f);
        YGNodeStyleSetFlexGrow(root_child2, 1.1f);
        YGNodeInsertChild(root, root_child2, 2);
        YGNodeCalculateLayout(root, float.NaN, float.NaN, YGDirection.LTR);
        Assert.Equal(0f, YGNodeLayoutGetLeft(root));
        Assert.Equal(0f, YGNodeLayoutGetTop(root));
        Assert.Equal(87f, YGNodeLayoutGetWidth(root));
        Assert.Equal(113f, YGNodeLayoutGetHeight(root));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child0));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child0));
        Assert.Equal(87f, YGNodeLayoutGetWidth(root_child0));
        Assert.Equal(59f, YGNodeLayoutGetHeight(root_child0));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child1));
        Assert.Equal(59f, YGNodeLayoutGetTop(root_child1));
        Assert.Equal(87f, YGNodeLayoutGetWidth(root_child1));
        Assert.Equal(30f, YGNodeLayoutGetHeight(root_child1));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child2));
        Assert.Equal(89f, YGNodeLayoutGetTop(root_child2));
        Assert.Equal(87f, YGNodeLayoutGetWidth(root_child2));
        Assert.Equal(24f, YGNodeLayoutGetHeight(root_child2));
        YGNodeCalculateLayout(root, float.NaN, float.NaN, YGDirection.RTL);
        Assert.Equal(0f, YGNodeLayoutGetLeft(root));
        Assert.Equal(0f, YGNodeLayoutGetTop(root));
        Assert.Equal(87f, YGNodeLayoutGetWidth(root));
        Assert.Equal(113f, YGNodeLayoutGetHeight(root));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child0));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child0));
        Assert.Equal(87f, YGNodeLayoutGetWidth(root_child0));
        Assert.Equal(59f, YGNodeLayoutGetHeight(root_child0));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child1));
        Assert.Equal(59f, YGNodeLayoutGetTop(root_child1));
        Assert.Equal(87f, YGNodeLayoutGetWidth(root_child1));
        Assert.Equal(30f, YGNodeLayoutGetHeight(root_child1));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child2));
        Assert.Equal(89f, YGNodeLayoutGetTop(root_child2));
        Assert.Equal(87f, YGNodeLayoutGetWidth(root_child2));
        Assert.Equal(24f, YGNodeLayoutGetHeight(root_child2));
        YGNodeFreeRecursive(root);
        YGConfigFree(config);
    }

    [Fact]
    public void rounding_total_fractial_nested()
    {
        var config = YGConfigNew();
        var root = YGNodeNewWithConfig(config);
        YGNodeStyleSetPositionType(root, YGPositionType.Absolute);
        YGNodeStyleSetHeight(root, 113.4f);
        YGNodeStyleSetWidth(root, 87.4f);
        var root_child0 = YGNodeNewWithConfig(config);
        YGNodeStyleSetHeight(root_child0, 20.3f);
        YGNodeStyleSetFlexGrow(root_child0, 0.7f);
        YGNodeStyleSetFlexBasis(root_child0, 50.3f);
        YGNodeInsertChild(root, root_child0, 0);
        var root_child0_child0 = YGNodeNewWithConfig(config);
        YGNodeStyleSetPosition(root_child0_child0, YGEdge.Bottom, 13.3f);
        YGNodeStyleSetHeight(root_child0_child0, 9.9f);
        YGNodeStyleSetFlexGrow(root_child0_child0, 1);
        YGNodeStyleSetFlexBasis(root_child0_child0, 0.3f);
        YGNodeInsertChild(root_child0, root_child0_child0, 0);
        var root_child0_child1 = YGNodeNewWithConfig(config);
        YGNodeStyleSetPosition(root_child0_child1, YGEdge.Top, 13.3f);
        YGNodeStyleSetHeight(root_child0_child1, 1.1f);
        YGNodeStyleSetFlexGrow(root_child0_child1, 4);
        YGNodeStyleSetFlexBasis(root_child0_child1, 0.3f);
        YGNodeInsertChild(root_child0, root_child0_child1, 1);
        var root_child1 = YGNodeNewWithConfig(config);
        YGNodeStyleSetHeight(root_child1, 10);
        YGNodeStyleSetFlexGrow(root_child1, 1.6f);
        YGNodeInsertChild(root, root_child1, 1);
        var root_child2 = YGNodeNewWithConfig(config);
        YGNodeStyleSetHeight(root_child2, 10.7f);
        YGNodeStyleSetFlexGrow(root_child2, 1.1f);
        YGNodeInsertChild(root, root_child2, 2);
        YGNodeCalculateLayout(root, float.NaN, float.NaN, YGDirection.LTR);
        Assert.Equal(0f, YGNodeLayoutGetLeft(root));
        Assert.Equal(0f, YGNodeLayoutGetTop(root));
        Assert.Equal(87f, YGNodeLayoutGetWidth(root));
        Assert.Equal(113f, YGNodeLayoutGetHeight(root));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child0));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child0));
        Assert.Equal(87f, YGNodeLayoutGetWidth(root_child0));
        Assert.Equal(59f, YGNodeLayoutGetHeight(root_child0));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child0_child0));
        Assert.Equal(-13f, YGNodeLayoutGetTop(root_child0_child0));
        Assert.Equal(87f, YGNodeLayoutGetWidth(root_child0_child0));
        Assert.Equal(12f, YGNodeLayoutGetHeight(root_child0_child0));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child0_child1));
        Assert.Equal(25f, YGNodeLayoutGetTop(root_child0_child1));
        Assert.Equal(87f, YGNodeLayoutGetWidth(root_child0_child1));
        Assert.Equal(47f, YGNodeLayoutGetHeight(root_child0_child1));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child1));
        Assert.Equal(59f, YGNodeLayoutGetTop(root_child1));
        Assert.Equal(87f, YGNodeLayoutGetWidth(root_child1));
        Assert.Equal(30f, YGNodeLayoutGetHeight(root_child1));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child2));
        Assert.Equal(89f, YGNodeLayoutGetTop(root_child2));
        Assert.Equal(87f, YGNodeLayoutGetWidth(root_child2));
        Assert.Equal(24f, YGNodeLayoutGetHeight(root_child2));
        YGNodeCalculateLayout(root, float.NaN, float.NaN, YGDirection.RTL);
        Assert.Equal(0f, YGNodeLayoutGetLeft(root));
        Assert.Equal(0f, YGNodeLayoutGetTop(root));
        Assert.Equal(87f, YGNodeLayoutGetWidth(root));
        Assert.Equal(113f, YGNodeLayoutGetHeight(root));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child0));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child0));
        Assert.Equal(87f, YGNodeLayoutGetWidth(root_child0));
        Assert.Equal(59f, YGNodeLayoutGetHeight(root_child0));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child0_child0));
        Assert.Equal(-13f, YGNodeLayoutGetTop(root_child0_child0));
        Assert.Equal(87f, YGNodeLayoutGetWidth(root_child0_child0));
        Assert.Equal(12f, YGNodeLayoutGetHeight(root_child0_child0));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child0_child1));
        Assert.Equal(25f, YGNodeLayoutGetTop(root_child0_child1));
        Assert.Equal(87f, YGNodeLayoutGetWidth(root_child0_child1));
        Assert.Equal(47f, YGNodeLayoutGetHeight(root_child0_child1));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child1));
        Assert.Equal(59f, YGNodeLayoutGetTop(root_child1));
        Assert.Equal(87f, YGNodeLayoutGetWidth(root_child1));
        Assert.Equal(30f, YGNodeLayoutGetHeight(root_child1));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child2));
        Assert.Equal(89f, YGNodeLayoutGetTop(root_child2));
        Assert.Equal(87f, YGNodeLayoutGetWidth(root_child2));
        Assert.Equal(24f, YGNodeLayoutGetHeight(root_child2));
        YGNodeFreeRecursive(root);
        YGConfigFree(config);
    }

    [Fact]
    public void rounding_fractial_input_1()
    {
        var config = YGConfigNew();
        var root = YGNodeNewWithConfig(config);
        YGNodeStyleSetPositionType(root, YGPositionType.Absolute);
        YGNodeStyleSetHeight(root, 113.4f);
        YGNodeStyleSetWidth(root, 100);
        var root_child0 = YGNodeNewWithConfig(config);
        YGNodeStyleSetHeight(root_child0, 20);
        YGNodeStyleSetFlexGrow(root_child0, 1);
        YGNodeStyleSetFlexBasis(root_child0, 50);
        YGNodeInsertChild(root, root_child0, 0);
        var root_child1 = YGNodeNewWithConfig(config);
        YGNodeStyleSetHeight(root_child1, 10);
        YGNodeStyleSetFlexGrow(root_child1, 1);
        YGNodeInsertChild(root, root_child1, 1);
        var root_child2 = YGNodeNewWithConfig(config);
        YGNodeStyleSetHeight(root_child2, 10);
        YGNodeStyleSetFlexGrow(root_child2, 1);
        YGNodeInsertChild(root, root_child2, 2);
        YGNodeCalculateLayout(root, float.NaN, float.NaN, YGDirection.LTR);
        Assert.Equal(0f, YGNodeLayoutGetLeft(root));
        Assert.Equal(0f, YGNodeLayoutGetTop(root));
        Assert.Equal(100f, YGNodeLayoutGetWidth(root));
        Assert.Equal(113f, YGNodeLayoutGetHeight(root));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child0));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child0));
        Assert.Equal(100f, YGNodeLayoutGetWidth(root_child0));
        Assert.Equal(64f, YGNodeLayoutGetHeight(root_child0));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child1));
        Assert.Equal(64f, YGNodeLayoutGetTop(root_child1));
        Assert.Equal(100f, YGNodeLayoutGetWidth(root_child1));
        Assert.Equal(25f, YGNodeLayoutGetHeight(root_child1));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child2));
        Assert.Equal(89f, YGNodeLayoutGetTop(root_child2));
        Assert.Equal(100f, YGNodeLayoutGetWidth(root_child2));
        Assert.Equal(24f, YGNodeLayoutGetHeight(root_child2));
        YGNodeCalculateLayout(root, float.NaN, float.NaN, YGDirection.RTL);
        Assert.Equal(0f, YGNodeLayoutGetLeft(root));
        Assert.Equal(0f, YGNodeLayoutGetTop(root));
        Assert.Equal(100f, YGNodeLayoutGetWidth(root));
        Assert.Equal(113f, YGNodeLayoutGetHeight(root));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child0));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child0));
        Assert.Equal(100f, YGNodeLayoutGetWidth(root_child0));
        Assert.Equal(64f, YGNodeLayoutGetHeight(root_child0));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child1));
        Assert.Equal(64f, YGNodeLayoutGetTop(root_child1));
        Assert.Equal(100f, YGNodeLayoutGetWidth(root_child1));
        Assert.Equal(25f, YGNodeLayoutGetHeight(root_child1));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child2));
        Assert.Equal(89f, YGNodeLayoutGetTop(root_child2));
        Assert.Equal(100f, YGNodeLayoutGetWidth(root_child2));
        Assert.Equal(24f, YGNodeLayoutGetHeight(root_child2));
        YGNodeFreeRecursive(root);
        YGConfigFree(config);
    }

    [Fact]
    public void rounding_fractial_input_2()
    {
        var config = YGConfigNew();
        var root = YGNodeNewWithConfig(config);
        YGNodeStyleSetPositionType(root, YGPositionType.Absolute);
        YGNodeStyleSetHeight(root, 113.6f);
        YGNodeStyleSetWidth(root, 100);
        var root_child0 = YGNodeNewWithConfig(config);
        YGNodeStyleSetHeight(root_child0, 20);
        YGNodeStyleSetFlexGrow(root_child0, 1);
        YGNodeStyleSetFlexBasis(root_child0, 50);
        YGNodeInsertChild(root, root_child0, 0);
        var root_child1 = YGNodeNewWithConfig(config);
        YGNodeStyleSetHeight(root_child1, 10);
        YGNodeStyleSetFlexGrow(root_child1, 1);
        YGNodeInsertChild(root, root_child1, 1);
        var root_child2 = YGNodeNewWithConfig(config);
        YGNodeStyleSetHeight(root_child2, 10);
        YGNodeStyleSetFlexGrow(root_child2, 1);
        YGNodeInsertChild(root, root_child2, 2);
        YGNodeCalculateLayout(root, float.NaN, float.NaN, YGDirection.LTR);
        Assert.Equal(0f, YGNodeLayoutGetLeft(root));
        Assert.Equal(0f, YGNodeLayoutGetTop(root));
        Assert.Equal(100f, YGNodeLayoutGetWidth(root));
        Assert.Equal(114f, YGNodeLayoutGetHeight(root));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child0));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child0));
        Assert.Equal(100f, YGNodeLayoutGetWidth(root_child0));
        Assert.Equal(65f, YGNodeLayoutGetHeight(root_child0));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child1));
        Assert.Equal(65f, YGNodeLayoutGetTop(root_child1));
        Assert.Equal(100f, YGNodeLayoutGetWidth(root_child1));
        Assert.Equal(24f, YGNodeLayoutGetHeight(root_child1));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child2));
        Assert.Equal(89f, YGNodeLayoutGetTop(root_child2));
        Assert.Equal(100f, YGNodeLayoutGetWidth(root_child2));
        Assert.Equal(25f, YGNodeLayoutGetHeight(root_child2));
        YGNodeCalculateLayout(root, float.NaN, float.NaN, YGDirection.RTL);
        Assert.Equal(0f, YGNodeLayoutGetLeft(root));
        Assert.Equal(0f, YGNodeLayoutGetTop(root));
        Assert.Equal(100f, YGNodeLayoutGetWidth(root));
        Assert.Equal(114f, YGNodeLayoutGetHeight(root));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child0));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child0));
        Assert.Equal(100f, YGNodeLayoutGetWidth(root_child0));
        Assert.Equal(65f, YGNodeLayoutGetHeight(root_child0));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child1));
        Assert.Equal(65f, YGNodeLayoutGetTop(root_child1));
        Assert.Equal(100f, YGNodeLayoutGetWidth(root_child1));
        Assert.Equal(24f, YGNodeLayoutGetHeight(root_child1));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child2));
        Assert.Equal(89f, YGNodeLayoutGetTop(root_child2));
        Assert.Equal(100f, YGNodeLayoutGetWidth(root_child2));
        Assert.Equal(25f, YGNodeLayoutGetHeight(root_child2));
        YGNodeFreeRecursive(root);
        YGConfigFree(config);
    }

    [Fact]
    public void rounding_fractial_input_3()
    {
        var config = YGConfigNew();
        var root = YGNodeNewWithConfig(config);
        YGNodeStyleSetPositionType(root, YGPositionType.Absolute);
        YGNodeStyleSetPosition(root, YGEdge.Top, 0.3f);
        YGNodeStyleSetHeight(root, 113.4f);
        YGNodeStyleSetWidth(root, 100);
        var root_child0 = YGNodeNewWithConfig(config);
        YGNodeStyleSetHeight(root_child0, 20);
        YGNodeStyleSetFlexGrow(root_child0, 1);
        YGNodeStyleSetFlexBasis(root_child0, 50);
        YGNodeInsertChild(root, root_child0, 0);
        var root_child1 = YGNodeNewWithConfig(config);
        YGNodeStyleSetHeight(root_child1, 10);
        YGNodeStyleSetFlexGrow(root_child1, 1);
        YGNodeInsertChild(root, root_child1, 1);
        var root_child2 = YGNodeNewWithConfig(config);
        YGNodeStyleSetHeight(root_child2, 10);
        YGNodeStyleSetFlexGrow(root_child2, 1);
        YGNodeInsertChild(root, root_child2, 2);
        YGNodeCalculateLayout(root, float.NaN, float.NaN, YGDirection.LTR);
        Assert.Equal(0f, YGNodeLayoutGetLeft(root));
        Assert.Equal(0f, YGNodeLayoutGetTop(root));
        Assert.Equal(100f, YGNodeLayoutGetWidth(root));
        Assert.Equal(114f, YGNodeLayoutGetHeight(root));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child0));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child0));
        Assert.Equal(100f, YGNodeLayoutGetWidth(root_child0));
        Assert.Equal(65f, YGNodeLayoutGetHeight(root_child0));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child1));
        Assert.Equal(64f, YGNodeLayoutGetTop(root_child1));
        Assert.Equal(100f, YGNodeLayoutGetWidth(root_child1));
        Assert.Equal(24f, YGNodeLayoutGetHeight(root_child1));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child2));
        Assert.Equal(89f, YGNodeLayoutGetTop(root_child2));
        Assert.Equal(100f, YGNodeLayoutGetWidth(root_child2));
        Assert.Equal(25f, YGNodeLayoutGetHeight(root_child2));
        YGNodeCalculateLayout(root, float.NaN, float.NaN, YGDirection.RTL);
        Assert.Equal(0f, YGNodeLayoutGetLeft(root));
        Assert.Equal(0f, YGNodeLayoutGetTop(root));
        Assert.Equal(100f, YGNodeLayoutGetWidth(root));
        Assert.Equal(114f, YGNodeLayoutGetHeight(root));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child0));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child0));
        Assert.Equal(100f, YGNodeLayoutGetWidth(root_child0));
        Assert.Equal(65f, YGNodeLayoutGetHeight(root_child0));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child1));
        Assert.Equal(64f, YGNodeLayoutGetTop(root_child1));
        Assert.Equal(100f, YGNodeLayoutGetWidth(root_child1));
        Assert.Equal(24f, YGNodeLayoutGetHeight(root_child1));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child2));
        Assert.Equal(89f, YGNodeLayoutGetTop(root_child2));
        Assert.Equal(100f, YGNodeLayoutGetWidth(root_child2));
        Assert.Equal(25f, YGNodeLayoutGetHeight(root_child2));
        YGNodeFreeRecursive(root);
        YGConfigFree(config);
    }

    [Fact]
    public void rounding_fractial_input_4()
    {
        var config = YGConfigNew();
        var root = YGNodeNewWithConfig(config);
        YGNodeStyleSetPositionType(root, YGPositionType.Absolute);
        YGNodeStyleSetPosition(root, YGEdge.Top, 0.7f);
        YGNodeStyleSetHeight(root, 113.4f);
        YGNodeStyleSetWidth(root, 100);
        var root_child0 = YGNodeNewWithConfig(config);
        YGNodeStyleSetHeight(root_child0, 20);
        YGNodeStyleSetFlexGrow(root_child0, 1);
        YGNodeStyleSetFlexBasis(root_child0, 50);
        YGNodeInsertChild(root, root_child0, 0);
        var root_child1 = YGNodeNewWithConfig(config);
        YGNodeStyleSetHeight(root_child1, 10);
        YGNodeStyleSetFlexGrow(root_child1, 1);
        YGNodeInsertChild(root, root_child1, 1);
        var root_child2 = YGNodeNewWithConfig(config);
        YGNodeStyleSetHeight(root_child2, 10);
        YGNodeStyleSetFlexGrow(root_child2, 1);
        YGNodeInsertChild(root, root_child2, 2);
        YGNodeCalculateLayout(root, float.NaN, float.NaN, YGDirection.LTR);
        Assert.Equal(0f, YGNodeLayoutGetLeft(root));
        Assert.Equal(1f, YGNodeLayoutGetTop(root));
        Assert.Equal(100f, YGNodeLayoutGetWidth(root));
        Assert.Equal(113f, YGNodeLayoutGetHeight(root));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child0));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child0));
        Assert.Equal(100f, YGNodeLayoutGetWidth(root_child0));
        Assert.Equal(64f, YGNodeLayoutGetHeight(root_child0));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child1));
        Assert.Equal(64f, YGNodeLayoutGetTop(root_child1));
        Assert.Equal(100f, YGNodeLayoutGetWidth(root_child1));
        Assert.Equal(25f, YGNodeLayoutGetHeight(root_child1));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child2));
        Assert.Equal(89f, YGNodeLayoutGetTop(root_child2));
        Assert.Equal(100f, YGNodeLayoutGetWidth(root_child2));
        Assert.Equal(24f, YGNodeLayoutGetHeight(root_child2));
        YGNodeCalculateLayout(root, float.NaN, float.NaN, YGDirection.RTL);
        Assert.Equal(0f, YGNodeLayoutGetLeft(root));
        Assert.Equal(1f, YGNodeLayoutGetTop(root));
        Assert.Equal(100f, YGNodeLayoutGetWidth(root));
        Assert.Equal(113f, YGNodeLayoutGetHeight(root));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child0));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child0));
        Assert.Equal(100f, YGNodeLayoutGetWidth(root_child0));
        Assert.Equal(64f, YGNodeLayoutGetHeight(root_child0));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child1));
        Assert.Equal(64f, YGNodeLayoutGetTop(root_child1));
        Assert.Equal(100f, YGNodeLayoutGetWidth(root_child1));
        Assert.Equal(25f, YGNodeLayoutGetHeight(root_child1));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child2));
        Assert.Equal(89f, YGNodeLayoutGetTop(root_child2));
        Assert.Equal(100f, YGNodeLayoutGetWidth(root_child2));
        Assert.Equal(24f, YGNodeLayoutGetHeight(root_child2));
        YGNodeFreeRecursive(root);
        YGConfigFree(config);
    }

    [Fact]
    public void rounding_inner_node_controversy_horizontal()
    {
        var config = YGConfigNew();
        var root = YGNodeNewWithConfig(config);
        YGNodeStyleSetPositionType(root, YGPositionType.Absolute);
        YGNodeStyleSetWidth(root, 320);
        YGNodeStyleSetFlexDirection(root, YGFlexDirection.Row);
        var root_child0 = YGNodeNewWithConfig(config);
        YGNodeStyleSetHeight(root_child0, 10);
        YGNodeStyleSetFlexGrow(root_child0, 1);
        YGNodeInsertChild(root, root_child0, 0);
        var root_child1 = YGNodeNewWithConfig(config);
        YGNodeStyleSetHeight(root_child1, 10);
        YGNodeStyleSetFlexGrow(root_child1, 1);
        YGNodeInsertChild(root, root_child1, 1);
        var root_child1_child0 = YGNodeNewWithConfig(config);
        YGNodeStyleSetHeight(root_child1_child0, 10);
        YGNodeStyleSetFlexGrow(root_child1_child0, 1);
        YGNodeInsertChild(root_child1, root_child1_child0, 0);
        var root_child2 = YGNodeNewWithConfig(config);
        YGNodeStyleSetHeight(root_child2, 10);
        YGNodeStyleSetFlexGrow(root_child2, 1);
        YGNodeInsertChild(root, root_child2, 2);
        YGNodeCalculateLayout(root, float.NaN, float.NaN, YGDirection.LTR);
        Assert.Equal(0f, YGNodeLayoutGetLeft(root));
        Assert.Equal(0f, YGNodeLayoutGetTop(root));
        Assert.Equal(320f, YGNodeLayoutGetWidth(root));
        Assert.Equal(10f, YGNodeLayoutGetHeight(root));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child0));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child0));
        Assert.Equal(107f, YGNodeLayoutGetWidth(root_child0));
        Assert.Equal(10f, YGNodeLayoutGetHeight(root_child0));
        Assert.Equal(107f, YGNodeLayoutGetLeft(root_child1));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child1));
        Assert.Equal(106f, YGNodeLayoutGetWidth(root_child1));
        Assert.Equal(10f, YGNodeLayoutGetHeight(root_child1));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child1_child0));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child1_child0));
        Assert.Equal(106f, YGNodeLayoutGetWidth(root_child1_child0));
        Assert.Equal(10f, YGNodeLayoutGetHeight(root_child1_child0));
        Assert.Equal(213f, YGNodeLayoutGetLeft(root_child2));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child2));
        Assert.Equal(107f, YGNodeLayoutGetWidth(root_child2));
        Assert.Equal(10f, YGNodeLayoutGetHeight(root_child2));
        YGNodeCalculateLayout(root, float.NaN, float.NaN, YGDirection.RTL);
        Assert.Equal(0f, YGNodeLayoutGetLeft(root));
        Assert.Equal(0f, YGNodeLayoutGetTop(root));
        Assert.Equal(320f, YGNodeLayoutGetWidth(root));
        Assert.Equal(10f, YGNodeLayoutGetHeight(root));
        Assert.Equal(213f, YGNodeLayoutGetLeft(root_child0));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child0));
        Assert.Equal(107f, YGNodeLayoutGetWidth(root_child0));
        Assert.Equal(10f, YGNodeLayoutGetHeight(root_child0));
        Assert.Equal(107f, YGNodeLayoutGetLeft(root_child1));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child1));
        Assert.Equal(106f, YGNodeLayoutGetWidth(root_child1));
        Assert.Equal(10f, YGNodeLayoutGetHeight(root_child1));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child1_child0));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child1_child0));
        Assert.Equal(106f, YGNodeLayoutGetWidth(root_child1_child0));
        Assert.Equal(10f, YGNodeLayoutGetHeight(root_child1_child0));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child2));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child2));
        Assert.Equal(107f, YGNodeLayoutGetWidth(root_child2));
        Assert.Equal(10f, YGNodeLayoutGetHeight(root_child2));
        YGNodeFreeRecursive(root);
        YGConfigFree(config);
    }

    [Fact]
    public void rounding_inner_node_controversy_vertical()
    {
        var config = YGConfigNew();
        var root = YGNodeNewWithConfig(config);
        YGNodeStyleSetPositionType(root, YGPositionType.Absolute);
        YGNodeStyleSetHeight(root, 320);
        var root_child0 = YGNodeNewWithConfig(config);
        YGNodeStyleSetWidth(root_child0, 10);
        YGNodeStyleSetFlexGrow(root_child0, 1);
        YGNodeInsertChild(root, root_child0, 0);
        var root_child1 = YGNodeNewWithConfig(config);
        YGNodeStyleSetWidth(root_child1, 10);
        YGNodeStyleSetFlexGrow(root_child1, 1);
        YGNodeInsertChild(root, root_child1, 1);
        var root_child1_child0 = YGNodeNewWithConfig(config);
        YGNodeStyleSetWidth(root_child1_child0, 10);
        YGNodeStyleSetFlexGrow(root_child1_child0, 1);
        YGNodeInsertChild(root_child1, root_child1_child0, 0);
        var root_child2 = YGNodeNewWithConfig(config);
        YGNodeStyleSetWidth(root_child2, 10);
        YGNodeStyleSetFlexGrow(root_child2, 1);
        YGNodeInsertChild(root, root_child2, 2);
        YGNodeCalculateLayout(root, float.NaN, float.NaN, YGDirection.LTR);
        Assert.Equal(0f, YGNodeLayoutGetLeft(root));
        Assert.Equal(0f, YGNodeLayoutGetTop(root));
        Assert.Equal(10f, YGNodeLayoutGetWidth(root));
        Assert.Equal(320f, YGNodeLayoutGetHeight(root));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child0));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child0));
        Assert.Equal(10f, YGNodeLayoutGetWidth(root_child0));
        Assert.Equal(107f, YGNodeLayoutGetHeight(root_child0));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child1));
        Assert.Equal(107f, YGNodeLayoutGetTop(root_child1));
        Assert.Equal(10f, YGNodeLayoutGetWidth(root_child1));
        Assert.Equal(106f, YGNodeLayoutGetHeight(root_child1));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child1_child0));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child1_child0));
        Assert.Equal(10f, YGNodeLayoutGetWidth(root_child1_child0));
        Assert.Equal(106f, YGNodeLayoutGetHeight(root_child1_child0));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child2));
        Assert.Equal(213f, YGNodeLayoutGetTop(root_child2));
        Assert.Equal(10f, YGNodeLayoutGetWidth(root_child2));
        Assert.Equal(107f, YGNodeLayoutGetHeight(root_child2));
        YGNodeCalculateLayout(root, float.NaN, float.NaN, YGDirection.RTL);
        Assert.Equal(0f, YGNodeLayoutGetLeft(root));
        Assert.Equal(0f, YGNodeLayoutGetTop(root));
        Assert.Equal(10f, YGNodeLayoutGetWidth(root));
        Assert.Equal(320f, YGNodeLayoutGetHeight(root));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child0));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child0));
        Assert.Equal(10f, YGNodeLayoutGetWidth(root_child0));
        Assert.Equal(107f, YGNodeLayoutGetHeight(root_child0));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child1));
        Assert.Equal(107f, YGNodeLayoutGetTop(root_child1));
        Assert.Equal(10f, YGNodeLayoutGetWidth(root_child1));
        Assert.Equal(106f, YGNodeLayoutGetHeight(root_child1));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child1_child0));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child1_child0));
        Assert.Equal(10f, YGNodeLayoutGetWidth(root_child1_child0));
        Assert.Equal(106f, YGNodeLayoutGetHeight(root_child1_child0));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child2));
        Assert.Equal(213f, YGNodeLayoutGetTop(root_child2));
        Assert.Equal(10f, YGNodeLayoutGetWidth(root_child2));
        Assert.Equal(107f, YGNodeLayoutGetHeight(root_child2));
        YGNodeFreeRecursive(root);
        YGConfigFree(config);
    }

    [Fact]
    public void rounding_inner_node_controversy_combined()
    {
        var config = YGConfigNew();
        var root = YGNodeNewWithConfig(config);
        YGNodeStyleSetPositionType(root, YGPositionType.Absolute);
        YGNodeStyleSetWidth(root, 640);
        YGNodeStyleSetHeight(root, 320);
        YGNodeStyleSetFlexDirection(root, YGFlexDirection.Row);
        var root_child0 = YGNodeNewWithConfig(config);
        YGNodeStyleSetHeightPercent(root_child0, 100);
        YGNodeStyleSetFlexGrow(root_child0, 1);
        YGNodeInsertChild(root, root_child0, 0);
        var root_child1 = YGNodeNewWithConfig(config);
        YGNodeStyleSetHeightPercent(root_child1, 100);
        YGNodeStyleSetFlexGrow(root_child1, 1);
        YGNodeInsertChild(root, root_child1, 1);
        var root_child1_child0 = YGNodeNewWithConfig(config);
        YGNodeStyleSetWidthPercent(root_child1_child0, 100);
        YGNodeStyleSetFlexGrow(root_child1_child0, 1);
        YGNodeInsertChild(root_child1, root_child1_child0, 0);
        var root_child1_child1 = YGNodeNewWithConfig(config);
        YGNodeStyleSetWidthPercent(root_child1_child1, 100);
        YGNodeStyleSetFlexGrow(root_child1_child1, 1);
        YGNodeInsertChild(root_child1, root_child1_child1, 1);
        var root_child1_child1_child0 = YGNodeNewWithConfig(config);
        YGNodeStyleSetFlexGrow(root_child1_child1_child0, 1);
        YGNodeStyleSetWidthPercent(root_child1_child1_child0, 100);
        YGNodeInsertChild(root_child1_child1, root_child1_child1_child0, 0);
        var root_child1_child2 = YGNodeNewWithConfig(config);
        YGNodeStyleSetWidthPercent(root_child1_child2, 100);
        YGNodeStyleSetFlexGrow(root_child1_child2, 1);
        YGNodeInsertChild(root_child1, root_child1_child2, 2);
        var root_child2 = YGNodeNewWithConfig(config);
        YGNodeStyleSetHeightPercent(root_child2, 100);
        YGNodeStyleSetFlexGrow(root_child2, 1);
        YGNodeInsertChild(root, root_child2, 2);
        YGNodeCalculateLayout(root, float.NaN, float.NaN, YGDirection.LTR);
        Assert.Equal(0f, YGNodeLayoutGetLeft(root));
        Assert.Equal(0f, YGNodeLayoutGetTop(root));
        Assert.Equal(640f, YGNodeLayoutGetWidth(root));
        Assert.Equal(320f, YGNodeLayoutGetHeight(root));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child0));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child0));
        Assert.Equal(213f, YGNodeLayoutGetWidth(root_child0));
        Assert.Equal(320f, YGNodeLayoutGetHeight(root_child0));
        Assert.Equal(213f, YGNodeLayoutGetLeft(root_child1));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child1));
        Assert.Equal(214f, YGNodeLayoutGetWidth(root_child1));
        Assert.Equal(320f, YGNodeLayoutGetHeight(root_child1));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child1_child0));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child1_child0));
        Assert.Equal(214f, YGNodeLayoutGetWidth(root_child1_child0));
        Assert.Equal(107f, YGNodeLayoutGetHeight(root_child1_child0));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child1_child1));
        Assert.Equal(107f, YGNodeLayoutGetTop(root_child1_child1));
        Assert.Equal(214f, YGNodeLayoutGetWidth(root_child1_child1));
        Assert.Equal(106f, YGNodeLayoutGetHeight(root_child1_child1));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child1_child1_child0));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child1_child1_child0));
        Assert.Equal(214f, YGNodeLayoutGetWidth(root_child1_child1_child0));
        Assert.Equal(106f, YGNodeLayoutGetHeight(root_child1_child1_child0));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child1_child2));
        Assert.Equal(213f, YGNodeLayoutGetTop(root_child1_child2));
        Assert.Equal(214f, YGNodeLayoutGetWidth(root_child1_child2));
        Assert.Equal(107f, YGNodeLayoutGetHeight(root_child1_child2));
        Assert.Equal(427f, YGNodeLayoutGetLeft(root_child2));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child2));
        Assert.Equal(213f, YGNodeLayoutGetWidth(root_child2));
        Assert.Equal(320f, YGNodeLayoutGetHeight(root_child2));
        YGNodeCalculateLayout(root, float.NaN, float.NaN, YGDirection.RTL);
        Assert.Equal(0f, YGNodeLayoutGetLeft(root));
        Assert.Equal(0f, YGNodeLayoutGetTop(root));
        Assert.Equal(640f, YGNodeLayoutGetWidth(root));
        Assert.Equal(320f, YGNodeLayoutGetHeight(root));
        Assert.Equal(427f, YGNodeLayoutGetLeft(root_child0));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child0));
        Assert.Equal(213f, YGNodeLayoutGetWidth(root_child0));
        Assert.Equal(320f, YGNodeLayoutGetHeight(root_child0));
        Assert.Equal(213f, YGNodeLayoutGetLeft(root_child1));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child1));
        Assert.Equal(214f, YGNodeLayoutGetWidth(root_child1));
        Assert.Equal(320f, YGNodeLayoutGetHeight(root_child1));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child1_child0));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child1_child0));
        Assert.Equal(214f, YGNodeLayoutGetWidth(root_child1_child0));
        Assert.Equal(107f, YGNodeLayoutGetHeight(root_child1_child0));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child1_child1));
        Assert.Equal(107f, YGNodeLayoutGetTop(root_child1_child1));
        Assert.Equal(214f, YGNodeLayoutGetWidth(root_child1_child1));
        Assert.Equal(106f, YGNodeLayoutGetHeight(root_child1_child1));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child1_child1_child0));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child1_child1_child0));
        Assert.Equal(214f, YGNodeLayoutGetWidth(root_child1_child1_child0));
        Assert.Equal(106f, YGNodeLayoutGetHeight(root_child1_child1_child0));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child1_child2));
        Assert.Equal(213f, YGNodeLayoutGetTop(root_child1_child2));
        Assert.Equal(214f, YGNodeLayoutGetWidth(root_child1_child2));
        Assert.Equal(107f, YGNodeLayoutGetHeight(root_child1_child2));
        Assert.Equal(0f, YGNodeLayoutGetLeft(root_child2));
        Assert.Equal(0f, YGNodeLayoutGetTop(root_child2));
        Assert.Equal(213f, YGNodeLayoutGetWidth(root_child2));
        Assert.Equal(320f, YGNodeLayoutGetHeight(root_child2));
        YGNodeFreeRecursive(root);
        YGConfigFree(config);
    }

}

