<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Radiant.Host.Tests</RootNamespace>
    <DebugType>embedded</DebugType>
    <IsTestProject>true</IsTestProject>
    <IsPackable>false</IsPackable>
    <AnalysisLevel>latest-Recommended</AnalysisLevel>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <NoWarn>$(NoWarn);CA1000;CA1002;CA1003;CA1033;CA1062;CA1303;CA1716;CA1720;CA1721;CA1812;CA2007;CA2225;CA1515;CA1707;CA5394;MSTEST0037</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Radiant.Host\Radiant.Host.csproj" />
  </ItemGroup>

  <ItemGroup>
    <AssemblyAttribute Include="Microsoft.VisualStudio.TestTools.UnitTesting.Parallelize" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
    <PackageReference Include="MSTest.TestAdapter" Version="4.0.2" />
    <PackageReference Include="MSTest.TestFramework" Version="4.0.2" />
    <PackageReference Include="coverlet.collector" Version="6.0.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
