// Copyright (c) Meta Platforms, Inc. and affiliates.
//
// This source code is licensed under the MIT license found in the
// LICENSE file in the root directory of this source tree.

// @generated by enums.py

using System;

namespace Facebook.Yoga
{
    [Flags]
    public enum Errata : uint
    {
        None = 0,
        StretchFlexBasis = 1,
        AbsolutePositionWithoutInsetsExcludesPadding = 2,
        AbsolutePercentAgainstInnerSize = 4,
        All = 2147483647,
        Classic = 2147483646,
    }

    public static class ErrataExtensions
    {
        public static string ToString(Errata e)
        {
            return YGErrataToString((YGErrata)(int)e);
        }

        private static string YGErrataToString(YGErrata errata)
        {
            switch (errata)
            {
                case YGErrata.None:
                    return "none";
                case YGErrata.StretchFlexBasis:
                    return "stretch-flex-basis";
                case YGErrata.AbsolutePositionWithoutInsetsExcludesPadding:
                    return "absolute-position-without-insets-excludes-padding";
                case YGErrata.AbsolutePercentAgainstInnerSize:
                    return "absolute-percent-against-inner-size";
                case YGErrata.All:
                    return "all";
                case YGErrata.Classic:
                    return "classic";
                default:
                    return "unknown";
            }
        }
    }

    [Flags]
    public enum YGErrata
    {
        None = 0,
        StretchFlexBasis = 1,
        AbsolutePositionWithoutInsetsExcludesPadding = 2,
        AbsolutePercentAgainstInnerSize = 4,
        All = 2147483647,
        Classic = 2147483646,
    }
}

