using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

namespace Radiant.Generators;

/// <summary>
/// Gives <c>Radiant.UI.Driver.RoleLocators</c> a method for each <c>SemanticsRole</c>, so tests select by
/// role without its name as a string (<c>Driver.Role.Button("Save")</c>). Runs on the driver itself, and
/// follows the enum as roles are added.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class RoleLocatorGenerator : IIncrementalGenerator
{
    private const string RoleLocators = "Radiant.UI.Driver.RoleLocators";
    private const string SemanticsRole = "Radiant.UI.Core.SemanticsRole";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var roles = context.CompilationProvider.Select(static (compilation, _) =>
        {
            // Only where RoleLocators is being compiled, and the roles can be seen.
            if (compilation.GetTypeByMetadataName(RoleLocators) is not { } locators
                || !SymbolEqualityComparer.Default.Equals(locators.ContainingAssembly, compilation.Assembly)
                || compilation.GetTypeByMetadataName(SemanticsRole) is not { } roleType)
            {
                return new EquatableArray<string>(ImmutableArray<string>.Empty);
            }
            return new EquatableArray<string>(roleType.GetMembers().OfType<IFieldSymbol>()
                .Where(f => f.HasConstantValue && f.Name != "None")
                .Select(f => f.Name)
                .ToImmutableArray());
        });
        context.RegisterSourceOutput(roles, static (output, names) =>
        {
            if (names.Count == 0)
            {
                return;
            }
            var code = new StringBuilder();
            code.AppendLine("// <auto-generated/>");
            code.AppendLine("#nullable enable");
            code.AppendLine();
            code.AppendLine("namespace Radiant.UI.Driver;");
            code.AppendLine();
            code.AppendLine("partial struct RoleLocators");
            code.AppendLine("{");
            foreach (var name in names)
            {
                var role = char.ToLowerInvariant(name[0]) + name.Substring(1);
                var cref = $"global::Radiant.UI.Core.SemanticsRole.{name}";
                code.AppendLine($"    /// <summary>Every element with the <see cref=\"{cref}\"/> role.</summary>");
                code.AppendLine($"    public global::Radiant.UI.Driver.Locator {name}() => Make(\"{role}\", null);");
                code.AppendLine();
                code.AppendLine($"    /// <summary>Elements with the <see cref=\"{cref}\"/> role labelled <paramref name=\"label\"/>, exactly.</summary>");
                code.AppendLine($"    public global::Radiant.UI.Driver.Locator {name}(string label) => Make(\"{role}\", global::Radiant.Host.AgentControlProtocol.TextMatch.Exact(label));");
                code.AppendLine();
                code.AppendLine($"    /// <summary>Elements with the <see cref=\"{cref}\"/> role whose label passes <paramref name=\"label\"/>.</summary>");
                code.AppendLine($"    public global::Radiant.UI.Driver.Locator {name}(global::Radiant.Host.AgentControlProtocol.TextMatch label) => Make(\"{role}\", label);");
                code.AppendLine();
            }
            code.AppendLine("}");
            output.AddSource("RoleLocators.g.cs", code.ToString());
        });
    }
}
