<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Radiant.Templates.Tests</RootNamespace>
    <Nullable>enable</Nullable>
    <DebugType>embedded</DebugType>
    <IsPackable>false</IsPackable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <EnforceCodeStyleInBuild>false</EnforceCodeStyleInBuild>
    <AnalysisLevel>latest-Recommended</AnalysisLevel>
    <NoWarn>CA1707,CA2263,CA1847,CA1861,CA1859</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Radiant.Templates\Radiant.Templates.csproj" />
    <ProjectReference Include="..\Radiant.Testing\Radiant.Testing.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
    <PackageReference Include="MSTest.TestAdapter" Version="3.7.0" />
    <PackageReference Include="MSTest.TestFramework" Version="3.7.0" />
    <PackageReference Include="coverlet.collector" Version="6.0.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\Radiant.Components.Tests\GoldenSheets.cs" Link="GoldenSheets.cs" />
  </ItemGroup>

</Project>

